linkedin/datahub-gma

.github/pull_request_template.md, build.gradle
It is rendered too differently from the rest of markdown for spotless to handle it. Whitespace is respected, which most markdown renderers don't do.
See below for how formatting is bad:
[Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly
[Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> Ignore formatting on GitHub markdown.

build.gradle, core-models/src/main/javaPegasus/com/linkedin/common/urn/TupleKey.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BaseUrnCoercer.java, validators/src/main/java/com/linkedin/metadata/validator/SnapshotValidator.java, validators/src/main/java/com/linkedin/metadata/validator/ValidationUtils.java
I've touched up a few easy to fix places, but have yet to fix everything / all modules. Might be wise to do this on a module by module basis.
#29
=> fix: start turning on werror for code.

build.gradle, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jUtil.java, gradle/checkstyle/checkstyle.xml, gradle/java-publishing.gradle, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSingleAspectEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSingleAspectEntityVersionedSubResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSingleAspectSearchableEntityResource.java
This should ensure our javadoc is actually valid HTML, and adheres to a slightly stricter style (taken from Google's).
=> fix: apply checkstyle JavaDoc checks.

docs/roadmap.md
I tried adding some points as "required" and others as "potential" (up for discussion). Because of the latter category, we need some extensive discussion around what we want in 1.0 since it isn't solid yet.
#6
=> doc: start adding the roadmap to 1.0.

testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/TestBulkListener.java
This is part of the Elasticsearch integration testing suite. #17
=> feat: Add a bulk listener implementation for use in tests.

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/internal/BaseGraphWriterDAO.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jQueryDAO.java, gradle/java-publishing.gradle
My previous RB for this I thought fixed it via checkstyle, but it did not. We need both checks, turns out.
I've turned on all warnings except missing warnings, we don't care about missing @tags if they don't add value.
=> fix: enable javadoc warnings

testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/BulkRequestsContainer.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/ReadAllDocumentsConfig.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/SearchIndex.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/TestBulkListener.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/TestSearchConfig.java
This adds a few search configs for testing, as well as the "SearchIndex" class which is a container object for most other things you'd want to use while testing (e.g. daos, bulk requests, etc).
#17
=> feat: add more classes for testing elasticsearch.

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/TestSearchConfig.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/TestSearchConfig.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityDocument.pdl
The default value of `DEFAULT_TERM_BUCKETS_SIZE_100` in `ESSearchDAO` might not always be good enough when aggregation happens on a high cardinality field. Using a high default instead is also not ideal because of potential query performance degradation. Instead, entities which have a rare use case of aggregating over high cardinality fields can use new setter method to override this default.
=> feat: Make max aggregation bucket size configurable

testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/ElasticsearchIntegrationTestExtension.java
The store is torn down after each class; we want the instance to live the life of the JVM.
=> fix: fix the lifecycle of the elasticsearch instances.

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/resources/UrnFilterQuery.json, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao/src/test/resources/UrnFilterQuery.json
Currently clients are using `comma` to provide multiple values a key can take while issuing filtered search query. Elasticsearch DAO splits the value by comma delimiter to populate the `terms` query. This does not work well when the value is an `Urn` with comma as some of the characters.
This change ensure we do not split the value by comma when the value is an Urn. Ideally we should be using the `OR` criterion to provide multiple values a key can take. But this will need changes on the client side before we stop supporting the `comma` feature to specify multiple values on the DAO side.
=> fix: do not split value of a filter by comma for an urn

build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/BaseReadDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/equality/AlwaysFalseEqualityTester.java, dao-api/src/main/java/com/linkedin/metadata/dao/equality/DefaultEqualityTester.java, dao-api/src/main/java/com/linkedin/metadata/dao/equality/EqualityTester.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/equality/DefaultEqualityTesterTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
=> fix: enable werror for dao-api.

build.gradle, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BrowsableClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/SearchableClient.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseBrowsableEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseSearchableEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseSingleAspectEntitySimpleKeyResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseVersionedAspectResourceTest.java
=> fix: turn on werror for restli-resources.

dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/ESUtils.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java
We split on commas in a few places for some reason, not sure why. I've added more TODOs to stop the comma parsing.
#51
=> fix: actually fix commas in URN search queries not working

build.gradle, scripts/li-local-release.sh, scripts/local-release.sh
This will make it clearer what versions will be used; we don't publish SNAPSHOTs to bintray, so if you are using a SNAPSHOT version, it must be on your machine.
=> feat: update local publish scripts to publish a SNAPSHOT version

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESBulkWriterDAO.java
Not bumping the semi major version since this is under development and not yet used.
=> fix: remove use of deprecated APIs in bulk writer DAO.

build.gradle, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESAutoCompleteQueryForHighCardinalityFields.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESAutoCompleteQueryForLowCardinalityFields.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/browse/BrowseDAOTest.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/utils/SearchUtilsTest.java
=> fix: turn on werror for elasticsearch-dao

build.gradle, dao-api/build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/BaseQueryDAO.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jQueryDAO.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jQueryDAOTest.java
I also got rid of the tuple library while I was here, easier than trying to get the generics right :)
#29
=> fix: turn on werror for neo4j-dao

dao-api/src/main/java/com/linkedin/metadata/dao/BaseQueryDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESAutoCompleteQueryForHighCardinalityFields.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESAutoCompleteQueryForLowCardinalityFields.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/browse/BrowseDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/utils/SearchUtilsTest.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/asserts/BulkRequestsContainerAssert.java
=> fix new modules since last rebase

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/ImmutableLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/BarUrnPathExtractor.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/BazUrnPathExtractor.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/FooUrnPathExtractor.java
Hi, I research yours code and decided to make changes a small defects by my own view). If it is ok for you then I will continue do it:)
Main of this changes is checking for non-null resource before opening stream to warns NPE and reports that is problem.
And com.google.common.base.Charsets is deprecated since jdk 7, better to use standard java java.nio.charset.StandardCharsets. Thx:)
=> refactor: Added some raw types, checking for non-null resource before opening stream.

build.gradle, docs/how/releases/continuous-releases.md, gradle/release.gradle
Hello, 
I'd like to let you know that recently new properties has been added to Shipkit Changelog and Shipkit Auto Version plugins. The latter exposes new 'ext' property for getting previous revision: _project.ext.'shipkit-auto-version.previous-tag'._ Using this property makes code clearer.
Configuration in _release.gradle_ file can be also updated with 2 new Shipkit Changelog plugin properties:
1) `newTagRevision` that ensures predictable tagging (adding this property fixes shipkit/shipkit-changelog#46). _'GITHUB_SHA'_ that supplies the property, is an GH Action's env variable that exposes SHA of the commit that triggered the workflow.
2) Token that is set by `githubToken property` is used both to fetch and post via GH API. Earlier used _'readOnlyToken'_ and _'writeToken'_ properties are …
=> Update Shipkit plugins configuration

testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/ElasticsearchIntegrationTestExtension.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/SearchIndex.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/SearchIndexFactory.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/annotations/DocType.java
Needed for LI internally where datasets for legacy reasons did not use "doc" as the doc type.
Note for ES7 doc types are no longer a concept and so this API is only needed in 5.
=> feat: add @DocType annotation for ES5 tests.

testing/elasticsearch-dao-integ-testing-docker-7/src/test/java/com/linkedin/metadata/testing/ESSearchDaoIntegTest.java, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/autocompleteTemplate.json, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/mappings.json, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/queryTemplate.json, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/settings.json, testing/elasticsearch-dao-integ-testing-docker/src/test/java/com/linkedin/metadata/testing/ESSearchDaoIntegTest.java, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/autocompleteTemplate.json, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/mappings.json, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/queryTemplate.json, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/settings.json, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/PizzaUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/PizzaUrnCoercer.java, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaSearchDocument.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaSize.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaUrn.pdl
Note the existing test model (BarSaerchDocument) is a little too vague and only had one field. Rather than expand it, I figured I'd make a more congrete and silly piece of test data for Pizzas.
Note: tests are the same across 5 and 7. Which makes sense as the DAO API did not change across versions.
=> feat: add integration tests for ES Search DAO.

build.gradle
We seem to be experiencing flaky builds on datahub (CI/CD fails on PRs: e.g. https://github.com/linkedin/datahub/pull/2084/checks)
specifically:
Execution failed for task ':gms:impl:integrationTest'
and the root cause seems to be: https://github.com/testcontainers/testcontainers-java/issues/3574
Upgrading to 1.15.1 hoping that this fixes it 🤞
=> fix: Upgrade testcontainers dependency to 1.15.1

testing/elasticsearch-dao-integ-testing-docker/src/main/java/com/linkedin/metadata/testing/ElasticsearchContainerFactoryDockerImpl.java
We've been seeing datahub integration tests fail on Linux machines (e.g. https://github.com/linkedin/datahub/issues/2088). The core reason for this issue is that production deployments of ElasticSearch require some [extra configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) on Linux machines.
However, we don't need a production deployment for integration tests, and as per [the ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode), we can use single-node mode to bypass these checks and make the tests succeed on Linux-based distros.
Note that this is already done in the es-7 directories: https://github.com/linkedin/datahub-gma/blob/e7bb1d96f2b822658d3390c493204ad1ec5194ee/testing/elastics …
=> fix: Use ElasticSearch in single-node mode

.github/workflows/release.yml
I forgot github secrets are not visible to the workflow environment unless explicitly set.
=> Pass artifactory secrets to workflow.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
UNION ALL can be much more performant than OR, and the mysql team at LI has indicated this query is cauasing performance issues. Switch to UNION ALL on their guidance.
=> fix: Use UNION for batch get rather than OR.

dao-api/src/main/pegasus/com/linkedin/metadata/query/SearchResultMetadata.pdl, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/BaseSearchConfig.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/TestSearchConfig.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/BaseSearchConfig.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/TestSearchConfig.java, testing/elasticsearch-dao-integ-testing-docker-7/src/test/java/com/linkedin/metadata/testing/ESSearchDaoIntegTest.java, testing/elasticsearch-dao-integ-testing-docker/src/test/java/com/linkedin/metadata/testing/ESSearchDaoIntegTest.java
Add the ability to highlight which part of the search document matched the query. This allows us to highlight any matches that do not show up in the preview (for instance, search for field names in a dataset will highlight the field name that matched the query)
In order for us to control the order of highlighted matches, the PDL matchMetadata field in SearchResultsMetadata holds a list of matched fields for each search element. 
*** Tests ***
Once GMS is deployed with this version of gma, 
http://localhost:8080/datasets?q=search&input=covid19
```
{
"metadata": {
"urns": [ ... ],
"matches": [
{
"matchedFields": [
{
"fieldValue": "bigquery-public-data.covid19_usafacts.deaths",
"fieldName": "name"
}
]
},
{
"matchedFields": [
{
"fieldValue": …
```
=> feat(search-by-field): Add match highlights to BaseSearchDAO

dao-impl/neo4j-dao/build.gradle, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAO.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAOTest.java
The current metrics we have I believe have a lot of overhead with respect to doing transformations and reflection before doing the actual query. I want to see how long our actual queries are taking.
Also replace some lambdas with for loops to make java profile heatmaps easier to read (each java stream lambda can add 5+ layers to the call stack).
=> feat: Add an interface to get lower level neo4j metrics

dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jUtil.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAO.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAOTest.java
Updates before would be total node overrides; so if a property was missing from the second update it would be deleted from the node. With MXE v5 we need to preserve properties not touched by updates.
=> fix: Make neo4j updates partial updates.

README.md
GMA onboarding guide is broken. This patch replaces it with the guide to onboard a data source.
=> fix: change GMA onboarding guide

dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAO.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jQueryDAOTest.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAOTest.java
Neo4j 4+ brings multiple DB support and we're planning to leverage this new feature. Writer DAO was only writing to the default DB. With this change, writer DAO could be configured to write to a specific graph DB by using `USE` keyword.
https://neo4j.com/docs/cypher-manual/4.1/clauses/use/
Unfortunately, we can't really write unit tests for at the moment. This needs bumping Neo4j test harness to 4+ which needs Java 11. And Java 11 build is blocked by ES7 migration.
=> feat(neo4j): Extend neo4j writer dao to write to a given db

dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAO.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jQueriesTransformer.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jQueryExecutor.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jQueryResult.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jQueryDAOTest.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAOTest.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jQueriesTransformerTest.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/internal/Neo4jTestHelper.java
There are really two steps here: taking our GMA models and transforming them to queries, and then executing queries.
This makes code do less, is more easily tested, and more reusable (single responsibility principle).
Also move out "test" code to demuddle the class.
---
note to reviewers: I acknowledge this is a big PR, and I'm happy to split it up if you want to scrutinize it more. But i really did just move some code around, at the fact that tests were only minimally edited should help show that :)
=> Refactor neo4j code to separate concerns.

testing/elasticsearch-dao-integ-testing-7/src/main/java/com/linkedin/metadata/testing/ElasticsearchIntegrationTestExtension.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/ElasticsearchIntegrationTestExtension.java
For static indices, we would end up calling testInstance.getClass().getClass().getResource() (indirectly). Somehow java 8 is fine with this and can locate the resource (off java.lang.Class), but java 11 is not okay with it (which is what I would expect).
Fix the code by being explicit about which class to use.
=> Fix resource loading in the ES test framework.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This change adds support for indexing array elements to different rows in SCSI.
Currently you can index all elements of an array. Indexing a specific array index or range of indices is not supported.
=> feat: add support for indexing array in SCSI

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Reverts linkedin/datahub-gma#103
Build fails on `./gradlew spotlessCheck`. I will revert this and resubmit again.
=> Revert "fix: use same urn class in both read and write path in SCSI"

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
use same urn class in write path as read for SCSI
=> fix: use same urn class in both read and write path in SCSI (#103)

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
There is a potential ConcurrentModificationException happening while multiple requests to perform delta update concurrently in the non-thread-safe hashMap,  using the ConcurrentHashMap to avoid the race condition instead.
=> fix: Use ConcurrentHashMap to avoid the race condition leading ConcurrentModificationException.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
Start using optimistic locking to prevent [lost updates](https://www.avaje.org/occ.html) in Ebean dao. The feature is flag guarded for now. After testing it in production, the plan is to make it the default behavior going forward.
=> feat: Use optimistic locking for db updates in ebean dao

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
In the post-update hook, one of the use cases is to call the `updateLocalIndex` function. This PR changes the signature of the `updateLocalIndex` function to public, so it can be called in the hook.
=> feat: make updateLocalIndex public

build.gradle
Version 4.24.8 of the library fails the build with below exception. Using the exact version of 4.24.5 builds fine in my local. 4.24.5 is also the latest version according to [maven repository](https://mvnrepository.com/artifact/org.jfrog.buildinfo/build-info-extractor-gradle).
```
* What went wrong:
A problem occurred configuring root project 'datahub-gma'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not find org.jfrog.filespecs:file-specs-java:1.0.0.
Searched in the following locations:
- https://plugins.gradle.org/m2/org/jfrog/filespecs/file-specs-java/1.0.0/file-specs-java-1.0.0.pom
- https://jcenter.bintray.com/org/jfrog/filespecs/file-specs-java/1.0.0/file-specs-java-1.0.0.pom
- https://jcenter.bintray.com/org/jfrog/filespecs/file-specs-java/1.0.0/file-sp …
```
=> fix: Fixate build-info-extractor-gradle version to 4.24.5

dao-api/src/main/pegasus/com/linkedin/metadata/query/Condition.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexValue.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This change allows users to filter by a string array using the IN operator in SCSI. A user can specify an array and the aspect to filter on.
=> feat: add in filter criterion

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This change adds offset pagination to SCSI. A new listUrns function returns a ListResult with pagination information. 
The next step is to add a filter method for offset pagination in BaseEntityResource, which will be done in a separate PR.
=> feat: add offset pagination to SCSI

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
This change adds a new filter method for offset pagination in BaseEntityResource. It is a follow-up to https://github.com/linkedin/datahub-gma/pull/110.
=> feat: add filter for offset pagination

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataIndex.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
This change adds a new method to the DAO and resource to count aggregations. The aspect and path to be grouped/aggregated on can be passed in, and the count of the urns for each grouped value is returned. The returned value is a map of the field value to the count.
=> feat: add aggregation count to SCSI

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/utils/SearchUtilsTest.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java, dao-impl/elasticsearch-dao/src/test/java/com/linkedin/metadata/dao/utils/SearchUtilsTest.java
This fix to address the issue https://github.com/linkedin/datahub-gma/issues/114
=> fix: add 'CONTAIN' support in query builder

docs/advanced/finders-scsi.md
This change adds documentation for sorting, pagination, and count aggregation in the SCSI finders.
=> docs: add documentation for finders in scsi

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/MixedRecord.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/StringUnion.pdl
In ChartInfo.pdl, we have an array of unions:
https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/chart/ChartInfo.pdl#L52
However, this was not supported in GMA's extract field utils. This meant that we could not index this field in the graph or search service.
=> fix(field-extraction): supporting string union extraction in record utils

dao-api/src/main/java/com/linkedin/metadata/dao/utils/QueryUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/QueryUtilTest.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/Neo4jUtil.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jQueryDAOTest.java, dao-impl/neo4j-dao/src/test/java/com/linkedin/metadata/dao/Neo4jUtilTest.java
These methods are not Neo4j-specific so they can be moved out of Neo4jUtil. This removes Neo4jUtil imports from classes (in [datahub](https://github.com/linkedin/datahub)), that have no other reference to neo4j.
Besides moving these two methods into QueryUtils, this renames them to match existing methods in the target utils class.
Methods in Neo4jUtil are marked as deprecated.
=> refactor(dao/utils): Move createRelationshipFilter from Neo4jUtil to QueryUtils

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
Introduce infrastructure for pre-update hooks, motivated by the need for a pre-update hook to remove duplicate elements from certain aspects.
=> feat: add pre-update hooks to BaseLocalDAO

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/ESUtils.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/search/ESSearchDAOTest.java
Similar fix was done for ES5 was made here https://github.com/linkedin/datahub-gma/pull/57
=> fix: issue with commas in filters of search queries with ES7

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseVersionedAspectResourceTest.java
This change adds a Restli delete method to support soft deletion of an aspect. More details on the delete method can be found here https://linkedin.github.io/rest.li/user_guide/restli_server#delete
=> feat: add restli delete method to soft delete aspect

dao-impl/ebean-dao/gma-create-all.sql, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/resources/gma-create-all.sql, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
In the PR https://github.com/linkedin/datahub-gma/pull/130, we made the `metadata` column nullable to support soft deletion of aspects. Since changing/altering a column in MySQL to make it nullable entails a good amount of downtime (for large sized tables), we will rather use a placeholder string `DELETED` in this case to denote a soft deleted aspect. All APIs/interfaces in DAO will stay the same, only while saving in DB via EbeanLocalDAO we will store `DELETED` string when inserting a `null` metadata. Similarly while retrieving `DELETED` string from DB, we will interpret it as `null` metadata.
=> fix: use DELETED string literal for null metadata

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
We added a new field to `AspectEntry` in https://github.com/linkedin/datahub-gma/pull/139. Even though it has a default value, we need to ensure that the _old_ way of instantiating `AspectEntry` using `new` and without `isSoftDeleted` parameter, still works.
=> fix: support old constructor of AspectEntry class

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUnionAlias.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityUnionAlias.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/RelationshipUnionAlias.pdl
While setting aspects in aspect union, you could use aliases for different aspect classes. However currently GMA throws error when a union is defined using aliases. This change fixes it.
=> [fix] support alias in unions

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/DeltaUnionAlias.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityDeltaAlias.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntitySnapshotAlias.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/SnapshotUnionAlias.pdl
Similar to this https://github.com/linkedin/datahub-gma/pull/142, this PR adds support for the get method when union templates have aliases for the different records.
=> support for alias in unions for get method

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectBaz.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUnionComplex.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/MixedRecord.pdl
add support for unions of primitive and non-primitive types already supported by scsi (e.g. typerefs, arrays)
=> feat(scsi): add support for union types in getFieldValue

dao-api/src/main/pegasus/com/linkedin/metadata/dummy/DummyRecord.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaArrayAspect.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaEnumAspect.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaMapAspect.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaStringAspect.pdl, validators/build.gradle, validators/src/main/java/com/linkedin/metadata/validator/AspectValidator.java, validators/src/main/java/com/linkedin/metadata/validator/EntityValidator.java, validators/src/main/java/com/linkedin/metadata/validator/RelationshipValidator.java, validators/src/main/java/com/linkedin/metadata/validator/ValidationUtils.java, validators/src/test/java/com/linkedin/metadata/validator/ValidationUtilsTest.java
This change will ensure that aspects, relationships and entities can only be of type record. We assume this in our DAO, but currently don't validate the same.
=> fix: properly validate that aspects can only be of type record

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseMetadataEventProducer.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This PR adds an option to enable multiple aspects to be updated within a single transaction in the `BaseLocalDao`. This allows for atomic creation/updates of entities.
=> (feat) Update multiple aspects in one transaction

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
Hitted documents in groups aggregation are not used in any way but they compose the majority of payload from ES. Set size to 0 will only include total hits count without actual hitted documents. Verified with a snapshot version locally.
=> fix: do not include hits in groups aggregation

dao-api/build.gradle, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectUnionWithSoftDeletedAspect.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/SoftDeletedAspectCopy.pdl, validators/build.gradle, validators/src/main/java/com/linkedin/metadata/validator/AspectValidator.java, validators/src/main/java/com/linkedin/metadata/validator/ValidationUtils.java, validators/src/main/pegasus/com/linkedin/metadata/aspect/SoftDeletedAspect.pdl
Instead of storing a simple text/reserved keyword to represent soft deleted aspect, let us use json to represent the same.
=> fix: use json to store deleted aspect metadata

validators/build.gradle
In PR https://github.com/linkedin/datahub-gma/pull/158 we added a PDL file corresponding to soft deleted aspect in `validators` module. This change ensures we are generating data template for pegasus while building.
=> fix: expose generated data template

validators/build.gradle
An extension to https://github.com/linkedin/datahub-gma/pull/160 this change ensures that data template files are generated and exposed
=> fix: generate data template in validators

validators/build.gradle
Reverts linkedin/datahub-gma#162. We need to publish the normal jar as well.
=> Revert "fix: generate data template in validators"

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
fix: use RecordTemplate instead of String for comparing aspect with deleted aspect metadata
* cast the string value of the aspect into RecordTemplate object
* use the record template object for comparison to avoid formatting issues associated with string representation of json
=> fix: use RecordTemplate instead of String for comparing aspect with deleted aspect metadata

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java, dao-impl/neo4j-dao/src/main/java/com/linkedin/metadata/dao/internal/Neo4jGraphWriterDAO.java
`checkSameUrn` logic is common to all graph writer DAO. Extract it into an util class.
=> Refector shared logic into util class

dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
Some unit tests require advanced MySQL syntax such as 'generated column' which is not supported by most in-memory DB. Therefore, these tests require connections to a full-fledged MySQL DB.
If you would like to run these tests, please first establish a connection to a dev MySQL instance by running:
`ssh -L 3309:makto-db-313.corp.linkedin.com:3306 [your-username]-ld3.linkedin.biz`
Then run: `./gradlew build -Ptest-ebean-dao`
=> feat: reconfig ebean dao unit tests

dao-api/src/main/java/com/linkedin/metadata/dao/ListResult.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
* add .equals() methods to all objects that will be compared in these methods
* add sufficient units tests to ensure dual-read schema will properly catch mismatched results (between new and old schema)
=> fix(new schema): fix compare results methods

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql, dao-impl/ebean-dao/src/test/resources/schema-evolution-create-all.sql
Changed `LONGTEXT` to `JSON` type for storing metadata. 
According to MySQL manual:
```
The JSON data type provides these advantages over storing JSON-format strings in a string column:
Automatic validation of JSON documents stored in JSON columns. Invalid documents produce an error.
Optimized storage format. JSON documents stored in JSON columns are converted to an internal format that permits quick read access to document elements. When the server later must read a JSON value stored in this binary format, the value need not be parsed from a text representation. The binary format is structured to enable the server to look up subobjects or nested values directly by key or array index without reading all values before or after them in the document.
```
All existing unit tests passed.
=> fix: Minor fixes on SQL syntax in test scripts

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillMode.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/resources/schema-evolution-create-all.sql, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
bug before:
backfill method calls get() to get aspects to backfill. however, for the new schema, this get() will try to get from the new schema tables, which won't have the existing data in it (hence the whole point of needing to backfill). 
solution:
create separate backfill method that circumvents existing backfill logic.
=> fix(new schema): fix backfill api + minor bug fixes

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
- MariaDB does not support "CAST('value' AS JSON)" which we use in the check for soft deleted aspects:
CAST(a_aspect1 AS JSON) != '{"gma_deleted":"true"}'
- Instead, let's use JSON_EXTRACT which is supported in both MySQL and MariaDB syntax, with the same behavior.
JSON_EXTRACT(a_aspect1, '$.gma_deleted') IS NULL
This works since JSON_EXTRACT on a path which does not exist (as is the case of 'gma_deleted' when the aspect has not been soft deleted) returns NULL.
=> feat(new schema): adjust soft deletion check to support MariaDB syntax

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
- original code was causing some weird issues in a downstream service where the JSONObject(<Map>) constructor could not be found
- verified using EbeanLocalDAO and EbeanLocalAccess unit tests that this new implementation behaves the same as before
=> fix(new schema): use static toJSONString instead of JSONObject constructor

dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
JSONParser is not thread-safe: `Please note that JSONParser is NOT thread-safe.` http://miamarti.github.io/HorusFramework/javadoc/org/json/simple/parser/JSONParser.html
To make it thread safe, create new JSONParser in non-static method.
=> make JSONParser thread safe

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
Was seeing errors such as 
```
com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: 
javax.persistence.PersistenceException: Query threw SQLException:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND urn > 'urn:li:dataset:(urn:li:dataPlatform:espresso,mDataA1669941550060,D...' at line 2 
Query was:SELECT *, (SELECT COUNT(urn) FROM metadata_entity_dataset ) as _total_count FROM metadata_entity_dataset
AND urn > 'urn:li:dataset:(urn:li:dataPlatform:espresso,mDataA1669941550060,DEV)' LIMIT 100 OFFSET 0
```
The problem is that we were assuming that when using parameter `lastUrn` for `listUrns()`, we will already have a `WHERE` clause to append `AND urn > ...` …
=> fix(new schema): fix filter sql bug

dao-api/src/main/java/com/linkedin/metadata/dao/ListResult.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
- Add more details to compareResults logs
- Downgrade compareResults log levels from error to warn
- Fix bug which was causing false negatives (EbeanMetadataAspect createdFor can be null)
=> fix(new schema): improve compareResults methods (bug fix & detailed logs)

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
Seeing some false negative logs before when comparing old and new schema results because the EbeanMetadataAspect metadata check was a simple String.equals check. However, metadata is JSON in string form so the order of JSON mappings may be different between the different objects. Fixed by comparing JSONObjects, the underlying implementation of JSONObject.equals is AbstractMap.equals which compares all entry sets, ignoring order.
=> fix(new schema): fix EbeanMetadataAspect metadata field equality check

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUnion.pdl
This method should only be used in cases where data has already been ingested into the entity tables but not the local relationship tables. For example, this can happen when the entity tables were set up before the local relationship tables.
=> feat(new schema): add method to backfill local relationships from entity tables

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
We want to increase the timeout allowed for SCSI queries so that we can gather meaningful performance baseline numbers for the old schema. With the 5 seconds timeout currently, we are not able to get a full grasp of how slowly SCSI is performing.
For example, in the old schema, a query could timeout in 5s. In the new schema, it could succeed in 4s. Does that mean the new schema is 25% better than the old schema? Not necessarily. If we had let the old schema query run to completion, it could have taken 15s for all we know. This would be a 275% improvement. 
We don't want to increase the timeout too high though since we don't want to overload the DB. So 10s should be a good middle ground.
=> (new schema): EbeanLocalDAO SCSI query timeout increased from 5s -> 10s

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
To help address issue #136 .
Before:
batchGet would still return results for urns which do not exist in the db.
Now:
batchGet will throw a 404 if all urns passed in do not exist in the db.
If some or all of the urns exist, it will only return results for those that do exist in the db.
=> fix(batchGet): synchronize batchGet() behavior with get()

.github/workflows/release.yml, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/MultiHopsTraversalSqlGenerator.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql
Context: To support multi-master setup, we need to remove usage of hard deletes.
=> feat: Soft-delete local relationships

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/browse/BrowseDAOTest.java
Currently, ESBrowseDAO uses a `must_not` clause in its query to filter active datasets by the `removed` _(boolean)_ field. 
This is the clause:
```
"must_not": { "term": { "removed": "true" } }
```
This causes an issue wherein those entities for which the **removed** field itself is missing from their corresponding search documents would also get surfaced in the results. 
This is also in contrast to the **search** query results, wherein the queries primarily have a '**must**' clause for '**removed = false**'.
Changes in this PR are to fix this issue in the browse behaviour. This change will make sure that only entities successfully marked _(indexed)_ as `removed = false` would surface in the results.
- Update the 'buildQueryString' method in ESBrowseDAO
- Added corresponding unit test
=> fix(browse): fix browse query to include must clause for removed field

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java, dao-impl/elasticsearch-dao-7/src/test/java/com/linkedin/metadata/dao/browse/BrowseDAOTest.java
The change made in the earlier PR(236) was primarily from the perspective of 'dataset' entity that has the 'removed' field indexed in the documents. However, for any other gma entity which does not have the concept of indexing the 'removed' field, that change would break the browse experience as no documents would get returned for such an entity type.
Hence, reverting the commit.
=> Revert "fix(browse): fix browse query to include must clause for removed field"

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Current code wrap db calls in one transaction with one retry. It prevents new / dual schema from using the default max retry (which is 3). Below are different ways to reach `insert` method. They should all use the default max retry.
addMany (runInTransaction, 3 retries) -> aspectUpdateHelper -> addCommon -> saveLatest -> insert
add (runInTransaction, 3 retries) -> aspectUpdateHelper -> addCommon -> saveLatest -> insert
delete (runInTransaction, 3 retries) -> addCommon -> saveLatest -> insert
=> use default max retry

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
We have two `lastmodifiedon` timestamps. One is in the aspect json column (a_aspect) and the other one is on row level. Current entity table backfill method will populate the row level `lastmodifiedon` using same timestamp as in  a_aspect. In this example below, during the backfill the row level `lastmodifiedon` could be set as 2021-01-01.
```
a_aspectfoo 2021-01-01
a_aspectbar 2023-01-01
```
The row level `lastmodifiedon` on entity table should always use current time whenever the row is modified.
=> always use current time when setting row-level lastmodifiedon

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
We're seeing over more then 2T binlog stacked in mysql db in one day which exhausted disk space. After examining the content of binlog, majority of the data is from soft deletion of local relationship table. Existing SQL will update all the rows (thousands) even it's already soft deleted. We should only update the ones that's NOT softed deleted yet.
=> add deleted_ts is null check

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Context
This PR is for adding a temporary debugging code to help to diagnose a racing condition that result in duplicate (urn, aspect, version) records on job-gms. After the cause is found, we will revert the change made in this PR.
=> add temporary debug code to debug the duplicity

dao-api/src/main/pegasus/com/linkedin/metadata/events/BaseTrackingContext.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/events/IngestionTrackingContext.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/events/TrackingContext.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/MCEBarAspect.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/annotatedAspectBar/MetadataAuditEvent.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/annotatedAspectBar/MetadataChangeEvent.pdl, gradle-plugins/metadata-events-generator-lib/src/main/resources/AspectUnionEvent.rythm, gradle-plugins/metadata-events-generator-lib/src/main/resources/MetadataAuditEvent.rythm, gradle-plugins/metadata-events-generator-lib/src/main/resources/MetadataChangeEvent.rythm, gradle-plugins/metadata-events-generator-plugin/src/test/groovy/com/linkedin/metadata/gradle/MetadataEventsGeneratorPluginIntegTest.groovy
- This adds support for tracking context in MXE as the interface to propagate the tracking information for identifying the request lifecycle.
- Adding a new field is backward compatible if a default value is provided. The reader will substitute that default for missing data in records written with an older schema. At LinkedIn, we require that this new field is of a type that contains a union with null and that null be the default to allow readers to identify clearly records where the data is missing.
- Place the model in the dao-api module as it is event-specific.
=> feat: support of Tracking Context in MXE.

build.gradle, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
"""
`<feat>[getLatest()]: add support to use two alternative methods for checking record existence during record insertion`
Based off of logs introduced in a previous changeset, there is good reason to believe that `Ebean's EbeanServer.find(Class, Object)` method does not work accurately at scale, returning no matching existing records when it is clear that such a record exists. This appears to be the cause of mass duplicity introduced into the database. Luckily, Ebean has several ways to accomplish a task such as checking record existence, so this changeset attempts to leverage two of these in attempt to stop further duplicates from being introduced.
Might introduce breaking change in future if either (or both) of the alternative pathways is removed after adoption.
"""
- Added unit …
=> Add toggle-able logic for job-gms record retrieval

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseGenericAspectRoutingGmsClient.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/pegasus/com/linkedin/testing/Aspect.pdl, restli-resources/src/test/pegasus/com/linkedin/testing/AspectAttributes.pdl, restli-resources/src/test/pegasus/com/linkedin/testing/Value.pdl
This PR is to add support for more than one aspect routing per entity resource. Prior to this enhancement, we only allow one aspect  being routed to a different GMS service per entity. After this enhancement, we will allow multiple aspects being routed to other GMS services for better scale.
=> (feat) generic aspect routing support

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseTrackingMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/tracking/DummyTrackingManagerTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/tracking/TrackingUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java
* define new tracking states
* create BaseTrackingMetadataEventProducer abstract class, to emit MAEs with tracking context
* modify constructors to accept trackingManager and trackingProducer parameters
* modify existing upsert DAO methods to accept trackingContext parameter
=> feat(tracking): add tracking framework to DAO methods and MAE emission

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
- add a new constructor for BaseAspectRoutingResource with a dummy param to avoid the conflict with the existing constructor (which has been deprecated)
- added a few temporary logging lines for EBean to help with the job-gms duplicity issue.
=> (fix) fix collision with legacy constructor issue

dao-api/src/main/pegasus/com/linkedin/metadata/events/BaseIngestionFailureModel.pdl
- this pr is to create a base model that can be used as the dead letter queue schema in metadata ingestion pipeline. The pipeline will share a single queue
- this model should be able to help user locate failures with what, when, where, why and whom
=> feat: Create a base ingestion failure model.

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Mostly an innocuous bug (result in unnecessary error logs). 
- rename getRoutingAspects() to getValueFromRoutingGms() to differentiate the other method: getRoutingAspects()
- add a getRoutingAspects() selector before passing aspect for getValueFromRoutingGms(). Currently the downstream will process non-routing aspects and print out error message. But the exception will be caught and handle silently.
=> (fix) include routing aspect selector

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
`<refactor / feat> :` refactor logging to be more concise and consistent, introduce JDBC query for cross checking with Ebean results
Suggestions from @dnbaker surrounding logging conventions in https://github.com/linkedin/datahub-gma/pull/255 have been incorporated. In addition, a JDBC query has been introduced to be used in cross-checking against Ebean's results to determine if the duplicity issue arises from the Ebean layer.
NOTE that JDBC is _not_ added as a 4th Find Methodology; it's intentionally made to be run in parallel in order to allow cross-checking.
The end result of this PR is that _**preceding the existing logging**_ we will be able to see the results that JDBC "would have gotten" ... because if BOTH JDBC and Ebean return `null` then we can be assured that Ebean is not the …
=> Refactor logging, introduce JDBC

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityValue.pdl
- fix an issue that if only routing aspect is requested, the resource rendering will fail due to missing snapshot urn. [[restli example](https://sceptre.corp.linkedin.com/service-detail/datasets/resource/datasets/details#methods,get,permlinkId-68661442)]
- fix an issue that multi-routing-aspect request will fail the processing logic.
=> fix get single/multi routing aspect issue

dao-api/src/main/pegasus/com/linkedin/metadata/events/BaseIngestionFailureModel.pdl
- add an optional failureTime field to BaseIngestionFailureModel to indicate the time that failure happens
=> refactor: add failure ts to ingestion failure model

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, dao-impl/ebean-dao/src/test/resources/EBeanDAOUtilsTest.conf, dao-impl/ebean-dao/src/test/resources/ebean-dao-utils-create-all.sql
1st attempt of fixing job-gms duplicity issue. The fix includes
- removing out-of-date analysis code
- add EBean retry (Attempt 1) on search miss
- add Jdbc retry (Attempt 2) on search miss (not enabled yet)
=> first attempt of fixing job-gms duplicity issue

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillMode.pdl, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
- We want to support low volume backfill against the live es index. Currently, such request needs manual operation to switch es indexes, which is dangerous and requires quite effort. In reality, we can't even close an oncall ticket.
- As the continuation in https://github.com/linkedin/datahub-gma/pull/286#discussion_r1277752227, we considered 1) adding tag in MAE payload; vs 2) setting old value as null to bypass consumer check. Eventually decided to go with 2) as it doesn't impact the MAE payload and can be easily deprecated as we migrate to other secondary store.
- Implement 2) in `BaseAspectRoutingResource` and `BaseEntityResource`.
=> feat: Add a new backfill method that sets the old value as null in MAE

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, version.properties
disable MAEv4 emission by default. Can be turned on case-by-case if necessary.
=> disable MAEv4 emission by default

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
add "event submitted" process state for MxE so that the health metrics can calculate the kafka queuing delay.
=> add MxE submitted process state

gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/annotatedAspectBar/MetadataAuditEvent.pdl, gradle-plugins/metadata-events-generator-lib/src/main/resources/MetadataAuditEvent.rythm, gradle-plugins/metadata-events-generator-plugin/src/test/groovy/com/linkedin/metadata/gradle/MetadataEventsGeneratorPluginIntegTest.groovy
"Adding a new field is backwards compatible if a default value is provided. The reader will substitute that default for missing data in records written with an older schema. At LinkedIn, we require that this new field be of a type that contains a union with null and that null be the default to allow readers to identify clearly records where the data is missing."
go/schemacompatbility
=> fix(audit): make MAE AuditStamp field backwards compatible

dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
Local build will fail on M1 / M2 Apple computer. This is PR provides a solution to local build the datahub-gma
**Prerequisite**
Make sure you install MariaDB on your computer first.
```
brew install mariadb
```
Add these 3 lines of code if you're building on M1/M2 chip computer.
```
configurationBuilder.setBaseDir("/opt/homebrew");
configurationBuilder.setUnpackingFromClasspath(false);
configurationBuilder.setLibDir(System.getProperty("java.io.tmpdir") + "/MariaDB4j/no-libs");
```
Tested with `./gradlew build`
=> Fix local build on M1/M2 Apple computer

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseTrackingMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/IngestionUtils.java, dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillMode.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/IngestionUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
- start sending ingestionMode in backfill MAEs
- add `emitNoChangeMetadataAuditEvent` action with ingestionMode to support backfill into both live and backup index.
- deprecate `backfillWithNewValue` action
=> feat: add action emitNoChangeMetadataAuditEvent & add ingestionMode in mae

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
**Context**
There are cases in which aspects are defined in `metadata-models` but the SQL script has not been written in the GMS. After a metadata-models version bump in GMS, people start to query column that's not defined yet in entity table. For example, the batchGet method in BaseEntityResource. This leads to SQL errors. [Previous issue](https://linkedin-randd.slack.com/archives/CG4JHTZ3J/p1682961734486449) raised in support channel
=> Bug fix: Check column existence before query

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
This change is as port of the Cold Archive provide, which target for moving change history out of the online MySQL datastore. This change will provide a configurable figure at entity DAO level, that users can stop writing change history into metadata_aspect table after updating the entity_table (dual-write)
with this change log disabled, the behavior of the following DAO APIs will behave differently
* list aspect history, list versions by given urn or aspect type - it will only return at most 1 aspect (current version), whereas previously it will return all the aspect change histories
* version or time-based retention will not be applicable when change log is disabled.
=> disable change history during persistence

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/IngestionUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
Normal MAEv4 emission is disabled by default in previous PR. https://github.com/linkedin/datahub-gma/pull/291
In this PR, we disable MAEv4 emission on backfill path as well. 
And some minor refactors to improve code style.
=> Disable MAEv4 on backfill path

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
There is a bug with a recent PR #298 which is causing OptimisticLockException to be thrown. Essentially, getLatest is reading from the new schema (in new schema only mode) but updateWithOptimisticLocking is trying to apply optimistic locking on the old schema table using the timestamp returned from the getLatest call on the entity table. The timestamps in the old and new schema tables may be off by a few ms so the update will fail during timestamp comparation.
This PR aims to revert part of that PR by reading the old schema table during getLatest always UNLESS change log is disabled.
=> fix(new schema): read metadata_aspect during getLatest regardless of schema mode

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
This change is to fix a bug in the optimistic locking update, whereas in NEW/DUAL Schema mode, we use last_modified time getting from getLatest() on entity table to run the UPDATE WHEN last_modified = :oldTimestamp on aspect table. Even in most cases the last modified time between entity/aspect table are the same. However, this is not guaranteed. The fix is to write a new optimistic locking logic for entity tables. The logic is written updateWithOptimisticLocking and  we expect this method to behave as below 
1.  In OLD_SCHEMA mode, 
- getLatest runs over the aspect table
- updateWithOptimisticLocking() with compare-and-set latest version on aspect table.
- if updateWithOptimisticLocking fails, all the updates will be rollback
2. In NEW/DUAL schema model, when changeLog is enabled …
=> APA-93246 fix dual-write issue on update wiht optimitic locking

gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/MAEBarAspect.pdl, gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/AspectUnionEventSpec.java, gradle-plugins/metadata-events-generator-lib/src/main/resources/AuditUnionEvent.rythm, gradle-plugins/metadata-events-generator-lib/src/test/java/com/linkedin/metadata/generator/TestEventSchemaComposer.java
We already have support for union MCE. Similar idea can be extended to MAE. This PR add capability to generate union MAE schema.
=> feat(unoin schema): Genereate union MAE schema

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
Saw a huge spike in metagalaxy CPU utilization (80%+) at around 11/08 6pm. After further investigation, we've identified the likely RC to be this PR #304 . I've reverted the changes from that PR.
=> revert check column existence (0.4.11)

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/events/IngestionTrackingContext.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
Based on the last discussion, we'll be first implementing a naive approach where we compare `emitTime` against `lastmodifiedtime`. If `emitTime < lastmodifiedtime`, we'll discard the backfill event.
One scenario pointed out by Edwina where this approach might not be ideal:
```
1. MCE-1 for entity A goes into DLQ (emit time T1)
2. MCE-2 for entity A goes into DLQ (emit time T2)
3. backfill batches MCE-1 and MCE-2, and consolidates into MCE-2.
4. MCE-3 for entity A goes into DLQ (emit time T3)
5. backfill runs, and applies MCE-2 (modified time T4)
6. backfill runs for MCE-3 and is dropped, since T3 < T4.
```
We'll implement this approach and will keep the logic for the old schema.
Future tasks:
- Add `emitTime` column in the new schema and use that as comparison to whether we should do …
=> Add naive approach to backfilling

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
There should always be `order by` when using `limit ... offset ...` in SQL query. Otherwise, the result will be non-deterministic. If user does not provide sort criterion, then use urn column to sort by default.
=> fix(listUrns): default to order by urn if user does not provide sort criterion

gradle-plugins/metadata-annotations-lib/src/main/java/com/linkedin/metadata/annotations/GmaAnnotationParser.java, gradle-plugins/metadata-annotations-lib/src/test/java/com/linkedin/metadata/annotations/GmaAnnotationParserTest.java, gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/SchemaAnnotationRetriever.java, gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/SchemaGenerator.java
This change is a requirement for removing allow list in metadata-models-plugin MP, which currently uses AlwaysAllowList as a workaround to enable reuse of aspects. In case like that, the allow list check becomes trivial, so we wish to remove the check as a whole for Plugins that don't require it.
This change will let the allow list to be nullable, so when the Project doesn't have a GmaEntitiesAnnotationAllowList passed to datahub-gma, we simply skip the check.
=> make GmaEntitiesAnnotationAllowList nullable

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
This PR addressed a few issues:
1. make IndexFilter nullable when calling listUrns. Previously it can't be nullable because of SCSI constraint. 
2. decouple listUrns with lastUrn to use separate filter SQL because it doesn't need to know the total count.
=> Decouple listUrns with lastUrn to use seperate filter SQL

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/ListResultMetadata.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
This is related to the MCEv5 backfill project where events with `backfill = true` will be emitted and processed. We'd like to add a column called `emitTime` to denote the emit time of the MCE that last modified the aspect. This will work for new schema only.
In follow up PR's, we will write the `emitTime` (new schema only) as well as add backfill logic related to `emitTime`. The logic will look something like:
```java
if (latestAspectEmitTime > ingestionTrackingContext.getEmitTime()) {
// skip backfill
} else {
// proceed with backfill
}
```
=> Add emitTime to the read path

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityAgnosticResourceTest.java
- change `List<BackfillItem>` to `BackfillItem[]` in method signature since collection is not supported by rest.li
- wrap `Task` around `BackfillItem[]` in order to support aync call
=> refactor: update backfillMAE API signature

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticResource.java
- BaseLocalDao has four constructors and [2 dependencies](https://jarvis.corp.linkedin.com/codesearch/results?query=%22extends+BaseLocalDao%3C%22): EbeanLocalDao and EspressoDao (not in this repo).
- the update for EbeanLocalDao was completed for 2 constructors in #325 
- the constructor update for EspressoDao was completed
- it turns out the rest two constructors in BaseLocalDao are also used in EbeanLocalDao in dao factory, therefore this PR updates remaining constructors with urnClass
=> fix: update EbeanLocalDao constuctors with urnClass & minor update

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityAgnosticResourceTest.java
- in testing backfillMAE method, it happens that urns of the same entity will get skipped, suspect it's caused by the parallelStream, change it to stream
- add more logging for testing and verification
=> fix: replace parallelStream with stream in backfill mae && add logging

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
During (local) relationship update, the out dated relationships will be soft deleted from local relationship table by marking the delete_ts = now(). However, the local relationship query does not exclude soft deleted relationships. This PR is to resolve this bug. 
This is a mandatory required fix in TMS Lineage Migration
=> Exclude soft deleted relationships from local relationship query

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/ListResultMetadata.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
This is continuation of https://github.com/linkedin/datahub-gma/pull/328
This PR makes 2 changes:
- Persist `emitTime` to the new entity table if IngestionTrackingContext is provided
- Use `emitTime` when checking whether we should backfill the entity
If `oldEmitTime` is available _and_ smaller than new event's emit time -> backfill
If `oldEmitTime` is not available _and_ last modified time smaller than new event's emit time -> backfill
=> Persist emitTime from IngestionTrackingContext to the new entity tables and use emitTime during backfill

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
When calling listUrns with large page size such as 1000, the API would throw OOM exception.
```
Caused by: java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOfRange(Arrays.java:4030) ~[?:?]
at java.lang.StringCoding.decodeUTF8(StringCoding.java:710) ~[?:?]
at java.lang.StringCoding.decode(StringCoding.java:231) ~[?:?]
at java.lang.String.<init>(String.java:467) ~[?:?]
at com.mysql.cj.util.StringUtils.toString(StringUtils.java:1350) ~[com.linkedin.li-mysql-connector-java.li-mysql-connector-java-8.0.27.73.jar:8.0.27.73]
```
select * is not necessary as only urn column is read for listUrns API.
=> Only select urn is needed for listUrns API

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
Previous [PR](https://github.com/linkedin/datahub-gma/pull/304) has caused high CPU load due to heavy query to INFORMATION_SCHEMAS. And it has been reverted in PR 315.
This PR aims to fix it by caching the table columns in memory and query INFORMATION_SCHEMAS only in very first column existence check.
=> fix: heavy query on information_schemas cause high CPU load

dao-api/src/main/java/com/linkedin/metadata/dao/builder/BaseLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/BelongsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/PairsWithLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/ReportsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/VersionOfLocalRelationshipBuilder.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
This feature is to allow clear relationships from a given source entity. Context for this feature is to solve Issue 2 in this doc:
https://docs.google.com/document/d/1WwXdos5BR7cxpDzxpArofRgj0_cdD9QGmjiZj7pQd14/edit#heading=h.v2d5gj2wsv95
- [] Docs related to the changes have been added/updated (if applicable)
=> (feat) support clear relationship by source entity urn

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/BaseVersionedAspect.pdl, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
Adding BaseVersionedAspect.pdl. It can be included by other aspects to add semantic versioning to the aspect. 
**Context**: The Datahub backend can be updated with Kafka Metadata Change Events (MCEs). However MCEs with outdated metadata may be received by the backend, eg a developer testing an older version of a project. Thus we want to (1) add semantic versioning to aspects and (2) add logic for datahub to process MCEs based on the version of the MCE and aspect in backend. This PR covers (1).
**Internal design doc**: https://docs.google.com/document/d/1Von4_q_CtvGrdMDfWHHVCcqmGyFT9CMlmXoeZAO59Oo/edit?usp=sharing
* **Build test**: Tested with `./gradlew build` as part of github checks
=> feat: Add BaseVersionedAspect.pdl

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/BaseVersionedAspect.pdl
Fix typo in baseSemanticVersion schema
Build test: `./gradlew build` run as part of github check.
=> fix: baseSemanticVersion typo

dao-api/src/main/java/com/linkedin/metadata/dao/BaseSearchDAO.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java
Exposing ESSearchDAO's searchV2 in BaseSearchDAO
=> add searchV2 endpoint in BaseSearchDAO

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/BaseVersionedAspect.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/events/BaseIngestionMode.pdl
Adding BaseIngesitonMode.pdl. This record has a writeMode attribute will declare how the aspect metadata change events (MCEs) should be written to the backend.
For starters, we will allow MCEs to declare the following write modes:
- DEFAULT: Default write mode. Same behavior as not setting writeMode.
- OVERRIDE: Override checks that may skip metadata write (eg equality check).
- **Build test**: `./gradlew build` ran successfully
=> feat: Create BaseIngestionMode.pdl

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
MySQL columns are case insensitive. So `abc` and `aBC` are essentially same columns.
=> fix: toLowerCase when checking column existance

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanDAOConfig.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/MultiHopsTraversalSqlGenerator.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql
Adding support for having non-dollar('$') character in the MySQL virtual(generated) columns. Currently, the virtual columns are named as 'i_urn$platform' now we can also use '0' as the delimiter i.e the virtual column could be named 'i_urn0platform'. 
Added unit tests for all the changes.
=> Adding support for non dollar virtual columns names

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
Added a default constructor to `EbeanLocalRelationshipQueryDAO` to keep it backward compatible for other GMSes.
=> Added default constructor for EbeanLocalRelationshipQueryDAO for backward compatibility

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseSearchableEntityResourceTest.java
The searchV2 was created to support running the search (ES) with supporting more than 1 filter criteria.
=> add searchV2 in restli

dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillModels.pdl
- this PR added a `BackfillModels.pdl` that has `backfillItems: array[BackfillItem]`. It is for generating the class `BackfillItemArray` with the pegasus schema which is needed for development and yet does not exist in the project.
- ./gradlew build
- verified generated class:
```
@Generated(value = "com.linkedin.pegasus.generator.JavaCodeUtil", comments = "Rest.li Data Template. Generated from dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillModels.pdl.")
public class BackfillItemArray
extends WrappingArrayTemplate<BackfillItem>
{
private final static ArrayDataSchema SCHEMA = ((ArrayDataSchema) DataTemplateUtil.parseSchema("array[{namespace com.linkedin.metadata.backfill/**A model that represents an item in a backfill action.*/record BackfillItem{/**The urn to …
```
=> feat: generate BackfillItemArray with schema

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Fixed the `getWithExtraInfo` which was not using pagination, which was creating queries with 5000 Union statements. Also set the default value of queryCount as 100, and set the limitation on the setter method to not set above 100.
**In conversation with MySQL team to know the ideal pagination count, they suggested 12. 12 seems too low looking at the 5000 union ran today. Working with them to test it on test server or prod read-replica**
MySQL team suggested to have any number between 12-100, it's all guesses and it's difficult to get the exact one without proper metrics. Yang suggested to go with 50 for now, but we can change it one way or the other.
Made few changes to TMS:
- Added `dao.setQueryKeysCount(2);` to BaseLocalDaoFactory
- Commented ` …
=> Added querycount to getWithExtraInfo

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseTrackingMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducer.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOAspectVersionTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
- IngestionMode was previously enabled in `trackingProducer` for MAE. However, it is not supported in non-tracking producers.
- This pr added `ingestionMode` to the MAE for GMS that is using non-tracking producers.
=> feat: include ingestion mode in non-tracking producer

dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/BaseLambdaFunction.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/LambdaFunctionRegistry.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, gradle-plugins/metadata-annotations-lib/src/main/java/com/linkedin/metadata/annotations/GmaAnnotationParser.java, gradle-plugins/metadata-annotations-lib/src/test/java/com/linkedin/metadata/annotations/GmaAnnotationParserTest.java, gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/DeltaAnnotation.pdl, gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/DeltaEntityAnnotation.pdl, gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/GmaAnnotation.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectBar.pdl
BUG=[META-20210](https://jira01.corp.linkedin.com:8443/browse/META-20210)
- Support field-level delta annotation for pre-ingestion lambda as the convention of `@gma.delta.entities`
- Create lambda function interface and registry for customized implementations.
- Expose API to be used on DAO ingestion.
=> feat: parse field-level delta annotations.

testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BarUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BazUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BurgerUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/FooUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/PizzaUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/SingleAspectEntityUrn.java
This PR adds deserialize method in Urn java class to match with the Urn classes generated internally in Linkedin.
=> feat: add deserialize method for Urn java classes

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/BaseSemanticVersion.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/BaseVersionedAspect.pdl
This is required to use the BaseSemanticVersion directly as fieldType instead of BaseVersionedAspect.BaseSemanticVersion
This change should be backward compatible as the generated java class for BaseSemanticVersion would still be `com/linkedin/metadata/aspect/BaseSemanticVersion.java`
=> feat: Move BaseSemanticVersion to top level schema

.github/workflows/build-and-test.yml, build.gradle, codecov.yml
- This pr attempts to enable the code coverage report for changes in datahub-gma. For now, it does not block merging even if a change decreases the overall test coverage of the project.
- Here is what the coverage report should look like: https://docs.codecov.com/docs/quick-start#step-5-get-coverage-analysis-from-codecov
- Reference: https://docs.codecov.com/docs/quick-start
- ./gradlew build
=> feat. attempt to enable codecov for datahub-gma

gradle-plugins/metadata-events-generator-plugin/src/main/java/com/linkedin/metadata/gradle/tasks/GenerateMetadataEventsTask.java
Starting from Gradle 7, all task getter must be annotated with their usage. Since the getEntitiesAnnotationAllowList getter is not annotated currently, the @Internal is the best matching backward compatible annotation for it
Manually tested that the task works on Gradle 7
=> gradle-plugin: add property annotation to make task compatible with Gradle 7+

.github/pull_request_template.md, README.md, codecov.yml
- update codecov file to block PRs that decrease the coverage of the repo
- update pr template file
- add a badge for codecov in readme
- ./gradlew build
=> feat: start to block PR that decreases the coverage of the repo

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
- Add a dimension `errorName`. With this change, one should use `errorType` to represent the category, and use `errorName` for the specific name of the exception.
=> feat: add error name into the dimension

codecov.yml, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingGmsClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
currently, every client registered in the aspect routing manager will be used regardless of the entity. It will cause problems in backfill since we want a GMS to share the same routing manager.
With this pr, only clients that have same entity type as the aspectroutingresource will be used in the backfill.
=> bug fix - consider entity type when using aspect routing client in backfill

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/GenericLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/GenericMetadataProducer.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanGenericLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanGenericLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticAspectResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityAgnosticAspectResourceTest.java
Add backfill method into Generic DAO.
Unit tests
=> [Generic DAO][Part 2] Implement backfill method

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticAspectResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java
Restli Action has this constraint that return type cannot be CreateResponse. Change the return type `Task<Void>` to be same as other ingest method.
=> Fix return type for generic ingest API

validators/src/main/java/com/linkedin/metadata/validator/DeltaValidator.java
All other validators have been updated to no longer check for required fields in model schemas. This is a required change as we move from PDL to Proto since all fields in Proto are optional.
=> fix(schema validation): remove optional 'delta' field requirement from DeltaValidator

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
new findRelationships API, which doesn't require entity snapshot, is needed to support non-MG entities. This PR adds API signature and unit test placeholder for review purpose.
The old API only uses snapshot to extract the entity type and find the db table. We can just provide that entity urn in the function call.
The current findRelationships API in EbeanLocalRelationshipQueryDAO requires that the source, destination, and relationship type parameters are of type RecordTemplate (i.e. Snapshots in this case). Considering that we want to support relationships between both MG entities and non-MG entities (for the crew use case), we need to define a new findRelationships API in EbeanLocalRelationshipQueryDAO which does impose this restriction on the parameters.
mint build
META-20529
=> feat: add new findRelationships interface and unit test placeholder

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EntityType.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/OwnedBy.pdl
Implemented new findRelationships API that doesn't require snapshot.class as input AND supports non-MG entity (only crew for now).
Note that now entity as passed in as urn, and we will extract the entity type directly from it, which is not type-safe as snapshot. So extra validation is needed to check if an entity is actually MG. Two options I considered, one is to check if snapshot.class exists, and second is check the table name in db. This PR is following the latter.
Another change is nullability of entity and filter, the old API requires filters to be nonnull, but it still allows empty filter arrays. So I made it nullable, and also, entity and filter should both exists for the sql query to work.
change of old code:
1. rearranged param order for buildFindRelationshipSQL
2. modified …
=> feat: add new findRelationships API and unit tests

dao-api/src/main/pegasus/com/linkedin/metadata/query/EntityQueryFilter.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/RelationshipQueryFilter.pdl
The final goal is to add proto models of these two in metadata-models, but due to some setup issue with translated proto and native proto, we are advised to first revert proto back to pdl and add in OSS.
=> feat: add query filter models for gRPC API

dao-api/src/main/pegasus/pegasus/com/linkedin/metadata/query/EntityQueryFilter.pdl, dao-api/src/main/pegasus/pegasus/com/linkedin/metadata/query/RelationshipQueryFilter.pdl
last PR #392 did not resolve the issue when adding proto equivalent in metadata-models. Need to move it to pegasus namespace.
=> fix: move EntityQueryFilter and RelationshipQueryFilter package

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
findRelationships becomes an ambiguous reference when used as a dependency in TMS.
N/A
=> fix: ambiguous reference to overload methods

dao-api/src/main/pegasus/com/linkedin/metadata/internal/IngestionParams.pdl
Add TestMode into Ingestion Param. 
Usage: when the test mode is set to be true, the current ingestion will be persisted into {entity}_test and {relationship}_test table for data validation purposes. 
More details see [Model 2.0 Migration Validation](https://docs.google.com/document/d/1ZfYn6vIAHC8FMFSgX9hbo1DEJl4m2KMtXlfAXecQ2Bo/edit#heading=h.xvq3ckiykqos)
=> add testMode into IngestionParams

dao-api/src/main/java/com/linkedin/metadata/dao/internal/BaseRemoteWriterDAO.java
Add createAsset to remote write DAO. This API will be need by RestliRemoteWriterDAO implementation at metadata-models.
=> add create asset to remote write DAO

dao-api/src/main/pegasus/com/linkedin/metadata/internal/IngestionParams.pdl
Currently, in ingestion, we use two fields to carry context information: IngestionTrackingContext and IngestionParams.
This pr is proposing merging the two fields to simplify the interface to external users.
There is no change required for [ingestionWithTracking](https://jarvis.corp.linkedin.com/codesearch/result/?name=BaseEntityResource.java&path=datahub-gma%2Frestli-resources%2Fsrc%2Fmain%2Fjava%2Fcom%2Flinkedin%2Fmetadata%2Frestli&reponame=linkedin%2Fdatahub-gma#248) in restli DAOs.
For external facing ingestAsset in restli and grpc syntax, the signature will look like
ingestAsset(Urn, AssetValue, IngestionParams)
=> add IngestionTrackingContext to IngestionParams

dao-api/src/main/java/com/linkedin/metadata/dao/internal/BaseRemoteWriterDAO.java
remove IngestionTrackingContext from the create asset method to align with https://github.com/linkedin-multiproduct/metadata-models/pull/1039
=> remove IngestionTrackingContext from createAsset

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java
change getSearchQueryCollectionResult to be public method as there are dependencies from corp-gms, ai-metadata-gms ..etc
=> change getSearchQueryCollectionResult to be public method

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAsset.pdl
Loose the naming convention on the fields on models, to reflect the internal models to asset models from param and return types
=> fix: reflect the internal models to asset models from param and return types

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/RestliCompliantPreUpdateRoutingClient.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/ingestion/SamplePreUpdateRoutingClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/ingestion/SamplePreUpdateRoutingClient.java
Fixed RestliPreUpdateAspectRegistry ingestion bug by getting the registry from BaseLocalDAO
=> Fixed RestliPreUpdateAspectRegistry ingestion bug

.github/workflows/build-and-test.yml, .github/workflows/release.yml, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
Moved the skip logic inside preUpdateLambda check. That is, only skip ingestion when it has a prelambda registered.
Workflow failed because of deprecated version of actions/upload-artifact: updated to v3: Ref: https://github.com/reactjs/react.dev/issues/7148
mint build
added a unit test for this case
=> Fixed bug which stopped all current DatasetAccountableOwnership ingestion

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
There are cases when a user doesn't need to provide an urn for the destination. For example, they only specify the destination type (like "dataset") but without also providing a filter on the UrnField (like urn = "urn:li:dataset:foo"). The current implementation does not support this as it expects either an Urn or null for the source and destination entities. If null, there's no way to tell the API which type of destination to look for.
adjusted unit tests. ./gradlew build
=> fix(findRelationshipsV2): change source/dest params from Urn to String

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
- fix logging for pre update in BaseLocalDao
- explicitly initialize _restliPreUpdateAspectRegistry as null in start time
=> fix logging for pre update routing

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/ingestion/SamplePreUpdateAspectRegistryImpl.java, restli-resources/src/test/java/com/linkedin/metadata/restli/ingestion/SamplePreUpdateRoutingClient.java
Change the behavior of BaseAspectRoutingResource's ingestInternal method to write any routed aspects locally in addition to routing the request to another GMS.
1) Update ingestInternal and ingestAssetInternal with the same logic
2) Move resource-level pre-ingestion lambdas into the if statement which checks if an aspect has a registered routing client.
3) In the aspect routing branch of the if statement, also call a new local DAO API `addSimple` which will store the aspect locally without executing any pre-ingestion lambdas within BaseLocalDAO. This is to prevent the case where a pre-ingestion lambda is executed twice in one ingestion (one before the routing, one within the local DAO).
Update existing unit tests to expect dual-write behavior. Added some comments for context.
=> implement dual write in BaseAspectRoutingResource

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Context is the Proto Migration testing employs Dual-Write testing logic, and with `changelogEnabled = true`, it attempts to write 2 records to metadata_aspect with the same Primary Key.
In `BaseLocalDAO.java`: ([ref](https://github.com/linkedin/datahub-gma/blob/af0995a2cedb75170354fec79501b90a44c5e78c/dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java#L771))
```java
/**
* Same as above {@link #add(Urn, AspectUpdateLambda, AuditStamp, int)} but with tracking context.
*/
@Nonnull
public <ASPECT extends RecordTemplate> ASPECT add(@Nonnull URN urn, [AspectUpdateLambda](https://jarvis.corp.linkedin.com/codesearch/result/?name=BaseLocalDAO.java&path=datahub-gma%2Fdao-api%2Fsrc%2Fmain%2Fjava%2Fcom%2Flinkedin%2Fmetadata%2Fdao&reponame=linkedin%2Fdatahub-gma#139)<ASPECT> …
```
=> Fix for duplicate writing in test mode

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
Users who have received explicit permission to use this API may do so to follow the ingestion path where all pre-ingestion update lambdas are skipped. This is useful to prevent loops like `ingest() -> lambda -> ingest() -> lambda -> so on`. Instead, the path will be `ingest() -> lambda -> ingestSkipPreIngestionUpdates()`.
added a unit test
=> feat(dual-write): add new ingestSkipPreUpdates resource endpoints

dao-api/src/main/java/com/linkedin/metadata/dao/internal/BaseRemoteWriterDAO.java
Add 2 new create APIs to BaseRemoteWriterDAO.
rawCreate and rawCreateAsset, which are the same as the existing create methods (for snapshots and assets respectively) except they don't call any pre-, intra-, or post-ingestion updates.
=> feat(rawCreate): add rawCreate/rawCreateAsset methods to BaseRemoteWriterDAO

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql
To disable DAO dual write in test mode by leveraging clients' calls.
=> feat: disable test mode to dual write in dao.

dao-api/src/main/pegasus/com/linkedin/metadata/query/AspectField.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/BarAsset
Read column from aspect-alias instead of column annotation - part 1
This is Part 1 of the work, which takes additional parameter (assetType aka entityType) into the getAspectColumn method.
Part 2 of the work will be implementing a map which retrieve aspect-alias by assetType and aspect class
=> Read column from aspect-alias instead of column annotation - part 1

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/main/pegasus/com/linkedin/metadata/query/AspectField.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/GlobalAssetRegistry.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/GlobalAssetRegistryTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/BarAsset.pdl
this is the 2nd part of PR: https://github.com/linkedin/datahub-gma/pull/433.
it is using a reflection to load all the asset classes with an lazy loading cache to map the requested `aspect` to the `aspect_alias`, which is the DB column stored on the database.
TODO
1. The reflection of loading all the assets can be moved to Li's internal code, will need horizontal update on the GMSes
2. Need a comprehensive unit test on metadata-models to ensure the calculated aspect_alias names are matching the "column" annotation.
=> read column from aspect alias part 2

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java
add getAspectTypesFromAssetType to get all the aspect classes declared from a Asset class
=> add getAspectTypesFromAssetType method

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/GlobalAssetRegistry.java
fix a bug in the `GlobalAssetRegistry` class that caused the `preLoadInternalAssets` method to not be called during the instantiation of the class.
=> fix glboal asset registry instantiation issue

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java
add backward compatible APIs for get columns
=> fix: add backward compatible APIs for get columns

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Changed log level to warning for 404 for BaseAspectRouting
=> Changed log level to warning for 404

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/lix/LegacyResourceImpl.java, restli-resources/src/main/java/com/linkedin/metadata/restli/lix/RampedResourceImpl.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/lix/DummyResourceLixTest.java
1. Change default READ API behavior to Model 2.0
2. Consolidate resource-lix implementation into datahub-gma
3. add & fix unit tests
1. [P0] bump datahub-gms in metadata-models
2. [P0] bump corp-identity GMS or metric GMS with the following cleanup to make sure no regression
4. [P0] make sure AIM has getResource() to return LegacyResourceImpl(), so that AIM will be safe to bump metadata-models which has default READ API behavior changed to ramped. 
5. [P0] bump metadata-models on GMSes which needs to onboard new entities (e.g. service-gms, datahub-gms). So that new entities can get onboarded without using RampedResourceImpl()
6. [P1] bump metadata-models from all GMS with the cleanup
- remove the ResourceLixFactory from each GMS
- remove the _resourceLix, getResourceLix() …
=> Consolidate resource-lix into datahub-gma

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseBrowsableClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableClient.java
=> Add search flag into base clients

dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/GmaAnnotation.pdl, gradle-plugins/metadata-annotations-test-models/src/main/java/com/linkedin/testing/urn/BarUrn.java, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectBarWithRelationshipFields.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectFooWithRelationshipField.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedRelationshipBar.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedRelationshipFoo.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/BarUrn.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/BarUrn.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/FooUrn.pdl
Implement a util method to extract any relationship fields out of aspects. In a later PR, this util method will be used during relationship ingestion to retrieve relationships to ingest in place of relationship builders.
The logic relies on the assumption that all PDL relationship models are properly annotated with the `@gma.model = RELATIONSHIP` annotation.
added a unit test.
=> feat(model 2.0): implement extractRelationshipsFromAspect util method

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/AspectCallbackRoutingClient.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
add ingestion params into CallbackRoutingClientAPI
Unit tes. Also I add it as default method, so the existing client should not break
- [ x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> add ingestion params into CallbackRoutingClientAPI

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/AspectCallbackMapKey.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/AspectCallbackRegistry.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/ingestion/AspectCallbackMapKeyTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/ingestion/AspectCallbackRegistryTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
Every dao has the registry and lambda logic, and the aspect routing may only be needed for specific asset, so we can reduce the number of calls by filtering out using entity and aspect to check whether the routing client exists.
Unit test
=> Included Entity type in the routing map

dao-api/src/main/java/com/linkedin/metadata/dao/GenericLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanGenericLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanGenericLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityAgnosticAspectResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityAgnosticAspectResourceTest.java
Support deletion in `EbeanGenericLocalDAO` and `BaseEntityAgnosticAspectResource`
We need to have generic deletion support for annotation metadata.
Long-term wise, team decided to have deletion support in every grpc endpoint.
However, to meet the timeline of the annotation use case, a `delete` method will be added in the `BaseEntityAgnosticAspectResource` so that `annotationGms` resource can expose this action.
- added a `delete` method and not send MAE for updates
- update `queryLatest` and `backfill` methods to accommodate deleted data 
- unit test added
- ./gradlew build
=> feat: Support deletion in EbeanGenericLocalDAO and BaseEntityAgnosticAspectResource

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
`aspectUpdateHelper` allows to return NULL when `isSkipProcessing` enabled so there is no real DAO save happen.
However the `unwrapAddResult()`doesn't expect result as NULL so it hits NPE. Also both MAE producing and post update hook should not happen because no real DAO happens.
Thus add NULL for return. 
./gradlew idea
=> Fix: aspectUpdateHelper result is null due to isSkipProcessing enabled so unwrapAddResult() hits NPE

dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-drop-all.sql, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectBarWithRelationshipFields.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectFooWithRelationshipField.pdl, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUnion.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/AspectFooBarBaz.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/ReportsTo.pdl
Previously, there was a gap when using relationship builders where an aspect that was registered with a relationship builder could not be soft deleted since there was no agreed-upon way to remove relationships associated with that aspect.
Now, when deriving relationships directly from aspect metadata, we can handle soft deletion gracefully. When the source aspect is marked as soft deleted, also mark any of the relationships from the old aspect value (existing in the db) as deleted in the corresponding relationship tables.
Note on the large number of files changed in this PR. I had to add a new test aspect model which required making many minor changes to other unit tests. No need to closely review those minor changes.
added a unit test
=> soft delete relationships when aspects are soft deleted (ASPECT_METADATA only)

dao-api/build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, dao-api/src/test/resources/defaultValueAspect.json, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectWithDefaultValue.pdl
Add support for recursively set default value in test mode
Add unit test
Also this only change the behavior for test mode, will not affect the prod behavior at all
snapshot the version and deploy to local to make sure it works, but it won't change the data for things that already set to empty. 
- [X ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> add support for recursively set default value in test mode

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/GraphUtilsTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectWithRelationship.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/AssetWithRelationship.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/RelationshipV2Bar.pdl, validators/src/main/java/com/linkedin/metadata/validator/RelationshipValidator.java, validators/src/main/java/com/linkedin/metadata/validator/ValidationUtils.java
This PR is to ensure the EbeanLocalWriterDAO can support both relationship V1 and relationship V2.
The changes are in Schema Validation for Relationship v2, RecordUtils, ModelUtils, and GraphUtils.
Question though is `checkSameUrn` logic in GraphUtils.java. They are related to the removal option, and for some options, they check for source Urn. But in Relationship model v2, there is no source field. Should it just skip the check for source field for V2, or should it look at the belonging aspect to find the source Urn? I feel looking at belonging aspect can have problems too because one relationship can be included in multiple different aspects.
Unit test cases added.
=> support relationship v2

dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java
In the previous PR, pushed in duplicate code in [RecordUtilsTest.java](https://github.com/linkedin/datahub-gma/blob/master/dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java#L545) and caused build error https://github.com/linkedin/datahub-gma/actions/runs/11691202669/job/32557830316
This PR is to remove the duplicate `loadAspectBaz` and `mockRelationshipV2Bar`, and to fix the build issue.
```
...
BUILD SUCCESSFUL in 1m 24s
245 actionable tasks: 25 executed, 220 up-to-date
```
=> Remove duplicate code in RecordUtilsTest.java

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/BelongsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
In Model 1.0, when new relationships are ingested, existing relationships are handled (i.e. removed) according to user-defined removal options. There are 4 possible options:
1) REMOVE_NONE
2) REMOVE_ALL_EDGES_FROM_SOURCE
3) REMOVE_ALL_EDGES_TO_DESTINATION
4) REMOVE_EDGES_FROM_SOURCE_TO_DESTINATION
1. has no use cases and will no longer be supported.
2. will be the default
3. will no longer be supported. in 2.0, relationships must always be modeled such that the asset they are derived from is the source in the relationship.
4. has use cases in AIM but moving forward, it will be up to the user to replicate these now "non-default" behaviors via pre-ingestion lambdas. Essentially, whatever the user provides to us in the aspect model, we will ingest using REMOVE_ALL_EDGES_FROM_SOURCE behavior. …
=> feat(relationship 2.0): use REMOVE_ALL_EDGES_FROM_SOURCE by default for ingesting 2.0 relationships

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/GraphUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql
This PR is to support `processLocalRelationshipUpdates` for relationship model v2.
Changes include:
1. GraphUtils.java
- Pass source asset urn in the `checkSameUrn` method for model v2.
2. GraphUtilsTest.java
- Add test cases of model v2 into all scenarios
3. ModelUtils.java
- Make `isRelationshipInV2` methods public so they can be used in EbeanLocalRelationshipWriterDAO logic
4. EbeanLocalRelationshipWriterDAO.java
- Add new parameter source asset urn to methods `addRelationships`, `addRelationshipGroup`, and `processRemovalOption`. The logic for model v1 remains the same, but the logic changes to take the passed parameter for model v2.
- Update documents
- Remove unused constant strings
5. EbeanLocalRelationshipWriterDAOTest.java
- Add model v2 test cases to RemoveFromSource test cases, …
=> Add the process of Relationship V2 in EbeanLocalRelationshipWriterDAO

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
Enable default value fill in for all update behavior
We already did the test in test mode, verified that in dural write mode, it does not introduce too much latency, 2ms in general
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
=> Enable default value fill in for all update behavior

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-drop-all.sql, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/AspectFooBar.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/AspectFooBarBaz.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/BelongsToV2.pdl
I noticed the unit tests that were supposed to extract relationship from aspect were using V1 relationship model, which has the source urn in it unlike V2. So the logic tested was not really for relationship V2.
1. added BelongsToV2 model that doesn't have source urn and has union as destination (how v2 should be
2. changed aspect related unit tests to use BelongsToV2 
3. fixed removeRelationships logic to be able to handle V2 case by passing down the source urn
=> fix: make unit test use v2 + fix removeRelationships logic

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
Change the API we use to fill in the default value
The original way of fill in default value will fill in all the field with default value even they are not required. which means as long as the field is optional, we will fill in the default value for it. The  behavior is conflict with the way we do compare using DataTemplateUtil.areEqual(), which only fill in the default value for required field. We do compare using DataTemplateUtil.areEqual() to compare the existing value and new value to avoid duplicate write to database, so the original approach will make us to write to db for every request even it's essentially the same. 
In the new approach, we will use ValidateDataAgainstSchema.validate(model, new ValidationOptions(RequiredMode.FIXUP_ABSENT_WITH_DEFAULT, CoercionMode.NORMAL, …
=> Change the API we use to fill in the default value

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
Currently, these is a "bug" where aspects that have multiple relationship fields of the same relationship type will not have all of them persisted properly in the DB. This is because the current logic for extracting relationships from aspect fields keeps all the extracted relationships separate by the field it was derived from. Then, the relationships are ingested sequentially by each field name group. Relationships in 2.0 are ingested using REMOVE_ALL_EDGES_FROM_SOURCE so any earlier relationships will get overwritten by later relationships if the later ones are of the same type as the earlier ones. 
The new logic will group them by relationship class. Each relationship class will be processed sequentially. This way, there is never any overlap of types between different relationship …
=> fix(relationship 2.0): handle the case where aspects can have multiple fields with the same relationship type

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java
Small fix of getAspectClassNames to handle union alias, to unblock EbeanLocalRelationshipQueryDAO.findEntities. (related to recent change in #436 
The buggy behavior was that when aliases exists in the union type, this function will return the alias instead of the canonical name.
For example:
```
typeref EntityUnionAlias = union[
foo: EntityFoo,
bar: EntityBar
]
```
old code will return foo when we actually expects `com.linkedin.testing.EntityFoo`
added unit test
./graldew build
=> fix: getAspectClassNames to handle union alias

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
When ./getAsset on non-existing asset, it should throw 404 exception 
unit test
=> throw 404 exception when get non-existing asset

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-create-all.sql
Add `aspect` column to relationship tables so that during relationship deletion, only the relationships derived from the same aspect that is being ingested can be deleted. This is to prevent accidental deletion of relationships which can be derived from multiple aspects.
Added a flag `useAspectColumnForRelationshipRemoval` which defaults to false to be backwards compatible.
Updated relationship soft deletion so it always works now whenever an aspect is soft-deleted.
Did some code cleanup of the RelationshipSource enum which is no longer needed since it will always try to get relationships from relationship builders first before looking in the aspect.
add unit tests
=> fix(relationship 2.0): add aspect column to relationship tables and fix soft deletion

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectBarWithRelationshipFields.pdl
There is a bug in metadata-store integration tests:
```
com.linkedin.metadata.dao.RestliClientStatusException: com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: java.lang.ClassCastException: class com.linkedin.common.EntityComplianceAnnotation cannot be cast to class java.util.List (com.linkedin.common.EntityComplianceAnnotation is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
```
This is because RecordTemplates are first checked to see if they are relationships. If not, the previous logic will assume that they are lists. But this is not the case if they are other structs. The fix is to add a check to see if it is a list. If it's not, just return.
update unit test
=> fix(relationship): fix bug in extractRelationshipFromAspect

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
For the metadata_aspect table, we have seen multiple 0 version records for a certain (urn, aspect and LATEST_VERSION) for a certain entities in one of the GMSes which has createdon as part of the PK. Due to which, backfillRelationship indeterministically considers the first row and not the latest row.
In this PR, this issue is fixed by introducing "ORDER BY" clause on createdon in a descending order and return the first row, which will confirm that we only consider the latest row.
=> Fixing backfillRelationship for metadata_apsect

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Simple change to throw out exception to fail the ingest request when routing aspect fail, to avoid silent failure for ingest request
no need to test
=> Throw out exception to fail the ingest request when routing aspect fail

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
In new schema mode, the aspect table is not getting update with optimistic locking on the createdon column. As a result, the duplicate version 0 rows in job-gms are causing duplicate key exceptions even in new schema mode.
To fix, read the latest row from the aspect table, get the timestamp, and also perform an update using the old timestamp to match a single row in the aspect table.
=> fix(new schema): fix duplicate key exception for aspect table

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
Currently, backfillEntityTables API does not backfill the a_urn column. This is an oversight since we never expected to need to backfill this column and it cannot be backfilled like other aspect columns. Thus, the solution is to add it to the upsert SQL which is called in EbeanLocalAccess::add. 
=> fix(backfill): update a_urn column during entity table backfill

dao-api/src/main/java/com/linkedin/metadata/dao/exception/ModelValidationException.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
we had large amount of exceptions like this
```
com.linkedin.metadata.dao.exception.ModelValidationException: failed to get aspect alias for: com.linkedin.dataset.DatasetProperties from asset: class pegasus.com.linkedin.metadata.asset.GrpcMethodAsset:
at com.linkedin.metadata.dao.utils.SQLSchemaUtils.getColumnName(SQLSchemaUtils.java:225)
at com.linkedin.metadata.dao.utils.SQLSchemaUtils.getAspectColumnName(SQLSchemaUtils.java:131)
at com.linkedin.metadata.dao.utils.SQLSchemaUtils.getAspectColumnName(SQLSchemaUtils.java:151)
at com.linkedin.metadata.dao.EbeanLocalAccess.batchGetUnion(EbeanLocalAccess.java:179)
at com.linkedin.metadata.dao.EbeanLocalDAO.batchGetHelper(EbeanLocalDAO.java:1148)
at com.linkedin.metadata.dao.EbeanLocalDAO.batchGet(EbeanLocalDAO.java:1078)
at …
```
=> translate ModelValidationException to 4XX

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Catch duplicate entry exceptions during server.insert() due to race conditions.
Log at WARN level.
Exceptions from before:
```
Error[Duplicate entry 'urn:li:mlFeatureAnchor:(urn:li:mlFeatureVersion:(urn:li:mlFeatur' for key 'metadata_aspect.PRIMARY']
at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:46)
at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:223)
at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:83)
at io.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:49)
at io.ebeaninternal.server.core.PersistRequestBean.executeInsert(PersistRequestBean.java:1295)
at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:797)
at …
```
=> catch duplicate entry errors and silently fail

.github/workflows/build-and-test.yml, .github/workflows/check-format.yml, .github/workflows/release.yml
Build and release on GH actions is failing consistently with
```
Run sudo apt-get install libncurses5
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libncurses5
Error: Process completed with exit code 100.
```
This may be due to the recent Ubuntu 24.04 migration that GH is performing which affects all workflows using `ubuntu-latest`. Ref: https://github.com/actions/runner-images/issues/10636. The article recommends to downgrade to ubuntu 22.04 explicitly if running into issues.
build action on gh (which uses build-and-test.yml) succeeds
=> Update workflows to explicitly use ubuntu-22.04 instead of ubuntu-latest

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
Making  initMgEntityTypeNameSet public to directly use it in GQS to extract the assets for each DAO.
=> feat(SMO Relationship onboarding - HackWeek): Make initMgEntityTypeNameSet public

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
To access the _mgEntityTypeNameSet after calling initMgEntityTypeNameSet(), we need to add a public getter method in the EbeanLocalRelationshipQueryDAO class
=> feat(SMO relationship onboarding: Hack week): Add a getter method for mgEntityTypeNameSet

.github/workflows/build-and-test.yml, dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java
In order to support the new [Delete Aspect API](https://docs.google.com/document/d/1kLnZNiWTxSsMIJP9sPT8Oc0gVGXau9JR5WkUy3ze0Wk/edit?tab=t.0), a `deleteMany()` method (with default-parameter variants) was added.
DeleteMany will be used to support the following spec:
```proto
/** Delete one or more Aspects for an URN */ 
rpc deleteAspects(DeleteAspectFromASSETRequest) returns (DeleteAspectFromASSETResponse) { option (.si.methodType) = DELETE; }
message DeleteAspectFromASSETRequest { 
/** Request context */ 
si.RequestContext context = 1; 
/** The URN of the asset for which aspects are being deleted. */ 
URN urn = 2; 
/** The list of aspect names to delete. */ 
repeated string aspectNames = 3; }
```
Adjusted additional unit testing and added a new one.
=> (feat) Add deleteMany Dao method

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This PR builds off of https://github.com/linkedin/datahub-gma/pull/496 by adding the ability for `deleteMany()` to return a Collection of the deleted Aspects' contents. This is necessary due to the finding [here](https://docs.google.com/document/d/1kLnZNiWTxSsMIJP9sPT8Oc0gVGXau9JR5WkUy3ze0Wk/edit?tab=t.0#bookmark=id.18k6qo9kpty6).
added new unit testing :)
=> (feat) Add deleteWithReturn

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
Added null check for extracted aspect value.
For Graph queries, we are getting this Null Pointer Exception and analyzing the stack trace we found this could be a potential gap.
```
Error message:
NullPointerException: Cannot invoke "String.length()" because "content" is null,
Root cause:
java.lang.NullPointerException: Cannot invoke "String.length()" because "content" is null
at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1336)
at com.linkedin.data.codec.JacksonDataCodec.stringToMap(JacksonDataCodec.java:136)
at com.linkedin.metadata.dao.utils.RecordUtils.toRecordTemplate(RecordUtils.java:93)
at com.linkedin.metadata.dao.EbeanLocalRelationshipQueryDAO.constructSnapshot(EbeanLocalRelationshipQueryDAO.java:377)
at …
```
=> [Bug Fix] Added null check for extracted aspect value

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
Get rid of `deleteWithReturn()` and make returning something a part of the normal `delete()` call. This will eventually be propagated up to `metadata-graph-assets` so that a default-parameter-version of `delete()` can be used for simplicity.
adjusted unit testing
=> Refactor deletion

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql
In the case where the entity table also has a column called `deleted_ts`, there will be a SQL exception when trying to call findRelationships.
Added the column to an entity table used in unit tests. `./gradlew build` and verify that build passes
=> fix(relationship): fix ambiguous reference to deleted_ts column

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
Add some logs and a flag to toggle them on or off (default off) to help debug relationship backfill API.
N/A
=> feat(logs): add detailed logs to relationship backfill

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
- Updating the  sql statement for creating assets when `urnExtraction=true`. 
- `urnExtraction=true` is applicable when schema was updated to add a new column and this column needs to be populated on insert/update.
- Existing sql statement always contained the a_urn whereas the parameter was added only if urnExtraction=true causing parameter mismatch error:
```
java.sql.exception: No value set for parameter 4
```
- The `a_urn` substring should be added to sql formatting string only if `urnExtraction=true`
Previous SQL: (missing value for a_urn)
```
INSERT INTO <table_name> (urn, a_urn, a_aspect_0, a_aspect_1, lastmodifiedon, lastmodifiedby)VALUES (urn_value, a_aspect_0_value, a_aspect_1_value, lastmodifiedon_value, lastmodifiedby_value)
```
Fixed SQL: (urnExtraction=false)
```
INSERT INTO …
```
=> Handling urn creation in create sql

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/AssetRelationship.pdl
To support Relationship 2.0 models, which doesnt have source in the relationship itself, we need a new API to return the source in a wrapper class along with the relationship2.0 model.
The internal use is AssetRelationship = source + relationship2.0 (destination only). I didn't want to hardcode the class here, so I left it extendable. User can pass it any RecordTemplate as wrapper class, but the implementation is only for AssetRelationship now.
I added a wrapOptions map in case we want to have other wrapper types in the future. Currently, it acts as a guard to prevent people who doesn't know this API to accidentally use it.
unit tests with relationship1.0 and 2.0
=> [feat] add findRelationshipsV3 API (impl + unit tests)

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
The change adds a log statement to help debug a slow SQL query for GQS. 
* [`dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java`](diffhunk://#diff-933a0b10b98159027344837b1e885f2f4bb7c19d1c01afc9c236722b7e396d73L273-R274): Added a log statement to output the SQL query being executed in the `findRelationshipsV2V3` method.
=> feat(logs): Adding logs to Graph Query for debbugging

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
- Fixing bug for missing MAE emission from create method
- Create method does not re-use the same logic branch as the update. Thus the MAE emit method needs to be called from create method as well.
- Each aspect is processed iteratively and MAE is emitted for each.
- Updated unit test
=> Emit MAE for each updated aspect

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
Below exception was thrown when deploying a GMS that contains schema changes.
```
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /System/Volumes/Data/export/content/lid/apps/service-gms/dev-i001/file:/System/Volumes/Data/export/content/lid/apps/service-gms/dev-i001/tmp/jetty-0_0_0_0-12667-service-war_war-_-any-17316494254071221865/webapp/WEB-INF/lib/service-impl-17.1.91.jar!/db/evolution/service_gms/V32__add_column_fullsuggestedannotation.sql
```
This PR attempts to fix this bug.
unit test passed.
=> [fix] Fix NoSuchFileException

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTestWithoutServiceIdentifier.java
Add flag to enable/disable schema check.
This is needed to disable schema check for local testing purpose. In local testing, we generally want to execute all the scripts automatically.
unit test
=> Add flag to enable/disable schema check

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/AspectCallbackRoutingClient.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Expose AuditStamp to AspectCallbackRoutingClient as in restli world, we cannot easily get CallContext and AuditStamp easily outside the resources class. 
unit test
=> expose AuditStamp to AspectCallbackRoutingClient

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseTrackingMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/GenericMetadataProducer.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOAspectVersionTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducerTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanGenericLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanGenericLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
This PR adds MAE emission for deletion operations.
The main implementation methodology here is that a new variant of the `unwrapAddResult()` method is added with a `isDeletion` flag, which is called when a Delete is performed. Slightly different logic is then acted on.
In addition, this PR changes `@Nonnull newValue` --> `@Nullable newValue` in basically all locations that previous claim it as being Non-Null. This is done because:
1. This conceptually is aligned with the concept of a Delete operation, in which the "new value" is simply NULL.
2. We cannot keep it @Nonnull since that would imply attempting to instantiate an "empty" version of the Aspect class...
1. We cannot instantiate ASPECT with an empty value; it goes against Java's nature of "type erasure" when compiling for generified …
=> (feat) Add MAE Emission for Aspect Deletion

docs/what/mxev5.md, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/MAEBarAspect.pdl, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/mxe/bar/annotatedAspectBar/MetadataAuditEvent.pdl, gradle-plugins/metadata-events-generator-lib/src/main/resources/AuditUnionEvent.rythm, gradle-plugins/metadata-events-generator-lib/src/main/resources/MetadataAuditEvent.rythm, gradle-plugins/metadata-events-generator-plugin/src/test/groovy/com/linkedin/metadata/gradle/MetadataEventsGeneratorPluginIntegTest.groovy
BUG=[META-21843](https://jira01.corp.linkedin.com:8443/browse/META-21843)
_**Milestone 9.1**_
This PR ensures that MAE's are generated with its `newValue` as an optional field.
This is to align with the expected behavior for a "DELETE MAE" which intuitively has a "null" value here.
Discussion: https://docs.google.com/document/d/1s_VJNZgsZ6x1k_aHwRpQ8f_a44ETOFXm7tMgI5-AbKk/edit?pli=1&tab=t.0#bookmark=id.wjh19iwjejza
This is a residual work to the groundwork laid in https://github.com/linkedin/datahub-gma/pull/513 -- but was missed since it wasn't required there but will be required for corresponding changes in `metadata-models`.
updated unit testing
=> (refactor) Make NewValue optional in MAE

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
The aspectCallbackHelper takes Optional params where a null was being provided. This would lead to NPE
example:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "value" is null
```
Replacing null with `Optional.empty()` for proper handling.
local build
=> [fix]Replacing null with Optional.empty() for optional param

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
In this PR, we have changed the underlying SQL queries for batchGetUnion to use IN rather than UNION ALL for same aspect class. This change is done after SQL level investigation where we found that these queries were taking more time to execute - taking about 10-15 seconds depending on the number of urns.
UNION ALL scans the table each time for every individual query. We can replace it with IN which will scan the table once for all the urns and will have faster query performance.
We conducted tests comparing the performance of `UNION ALL` and `IN` for querying 5,000 and 10,000 URNs. The results clearly show that `IN` significantly improves query execution time.
| Test Scenario              | Execution Time (real) | Command Used | …
=> [fix] Updated batchGetUnion SQL query to use IN rather than UNION

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
We discovered that GQS queries which filters on the destination field of relationship tables were not performing as expected. They were using the wrong index(idx_destination), which was causing performance issues. So, we will force the use of the correct index`idx_destination_deleted_ts` by adding a FORCE INDEX hint to the queries.
I checked for source filtering, it's using the index efficiently - don't want to over-engineer it right now
- Ensure all the relationship table has the index `idx_destination_deleted_ts`
=> (Improvement) Adding Force Index for graph queries filtering on destination field of relationship tables

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
This PR is basically a partial revert of #518. In that PR, we were doing two things:
1. batching the INs to 200
2. Converting ORs to use IN
In this PR, we will revert part 1 and keep the part 2 where 
- it merges multiple EQUAL conditions on the same field into a single IN clause to reduce query complexity.
**Previously:**
```sql
urn = 'value1' OR urn = 'value2' OR urn = 'value3'
```
**Now:**
```sql
urn IN ('value1', 'value2', 'value3')
```
=> Reverting batching of INs in GQS

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
Updated the `buildFindRelationshipSQL` method in `EbeanLocalRelationshipQueryDAO.java` to compare the `urnField` of the `LocalRelationshipCriterion.Field` object with `DESTINATION_FIELD` before appending `FORCE_IDX_ON_DESTINATION` to the `sqlBuilder`.
Check the debugger section
=> (BugFix): Small bug in Forced Index Logic

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
Revert OR to IN - somehow didn't see any performance improvement - my theory says IN without batching would actually slow the query
=> Revert OR to IN

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/RelationshipLookUpContext.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
Add POC to enable option to include non-current edge in single hop query
Change the existing unit test, and also did snapshot and local deployment, verified that the existing behavior remains unchanged and new behavior works as expected
=> Add POC to enable option to include non-current edge in single hop query

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/AspectCallbackRoutingClient.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseTrackingMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/GenericMetadataProducer.java, dao-api/src/main/pegasus/com/linkedin/metadata/events/ChangeType.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
- Adding new method for Delete Asset: `deleteAll` for hard delete (deleting urn and all aspects from db table)
- Added `ChangeType_DELETE_ALL` to differentiate between asset vs aspect deletion. This will be used in sending MAE events. In case of asset delete the ChangeType will be set to DELETE_ALL. 
- Added new abstract method `produceAspectSpecificMetadataAuditEvent` to `BaseTrackingMetadatProducer` and method `produceAspectSpecificMetadataAuditEvent` to interface `GenericMetadataProducer`. With these methods, both the `oldValue` and `newValue` are `@Nullable`. The methods contain additional `ChangeType` param. So eventually, these methods can be used to emit MAEs on all db operations . for example
|Action| Null Values | ChangeType |
|------|-------|--------------|
|create|oldValue is …
=> (feat) Adding delete asset implementation

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
- TL;DR: Check if the aspect value is present before using `.get` and processing the DeleteResult.
- Error founf in API testing
<details>
<summary>Log: Line984 </summary>
```
Caused by: java.util.NoSuchElementException: No value present                                                                                                                     
at java.base/java.util.Optional.get(Optional.java:143)                                                                                                                              
at com.linkedin.metadata.dao.BaseLocalDAO.lambda$deleteCommon$11(BaseLocalDAO.java:984)                                                                                             
at java.base/java.util.HashMap.forEach(HashMap.java:1421) …
```
=> Check if aspect is present before processing delete result

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
This PR introduces optional dual-write support in BaseEntityResource by allowing a shadow DAO to be configured per resource.
✅ Key Changes:
- Added a new protected method:
```java
@Nullable
protected BaseLocalDAO<INTERNAL_ASPECT_UNION, URN> getShadowLocalDAO()
```
Returns null by default. Resources can override this to enable shadow writes.
- Updated the following ingestion methods to support dual-write if a shadow DAO is present:
``` java
ingestInternal(...)
rawIngestInternal(...)
ingestInternalAsset(...)
rawIngestAssetInternal(...)
```
In each case, the ingestion is done to both the primary and shadow DAOs if getShadowLocalDAO() is non-null.
🧪 Next Steps:
Resource classes like Demos.java can opt into dual-write by overriding getShadowLocalDAO() and injecting a second DAO.
./gradlew …
=> Enable optional dual-write support in BaseEntityResource via shadow DAO

validators/src/main/java/com/linkedin/metadata/validator/RelationshipValidator.java
remove the field type check on relationship models.
./gradlew build.
=> remove relationship field type validation

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
We allow NULL to be produced by user callback service so it indicates the aspect shouldn't be ingested into DAO.
Note: The Type cast on NULL won't through exception.
N/A
=> fix: skip ingestion when user callback service return updated aspect as NULL

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql
This PR enables DAO level de-duplication logic for non current relationship look up. Will use source, destination, and metadata.type (if exist, for example for downstreamof) to dedeup.
FYI
mariadb is not on the version that supports CTE (WITH keyword). I used another expression.
SQL generated:
```
SELECT * FROM (SELECT rt.*, ROW_NUMBER() OVER (PARTITION BY rt.source, rt.destination ORDER BY rt.lastmodifiedon DESC) AS row_num FROM metadata_relationship_downstreamof rt INNER JOIN metadata_entity_dataset dt ON dt.urn=rt.destination INNER JOIN metadata_entity_dataset st ON st.urn=rt.source  WHERE (dt.urn='urn:li:dataset:(urn:li:dataPlatform:gridTable,prod_learningadmin.categoryv2,PROD)') AND (st.urn='urn:li:dataset:(urn:li:dataPlatform:gridTable,u_llsins.temp_qa_358920_content_ …
```
=> [feat] history relationship dedup logic

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql
This is PR#1 in a series of PRs which will contain code changes to support usage of `deleted_ts` column in DAO methods for read and write.
What?
- Adding a check on `deleted_ts` column in dao level queries for exists() and filter() methods.
- Updating unit tests to check the query strings now include `deleted_ts` check.
- Updating test tables to have `deleted_ts` column with NULL as the default value.
Why?
- `deleted_ts` column is required for supporting delete operations on EGG databases. Instead of doing a hard delete using `DELETE FROM <table> where <some condition>`, the records to be deleted with have a non-null value for `deleted_ts` column indicating the record has been deleted. It will actually be removed from the table periodically by a scheduled purge job. Till then, records …
=> Updating exists() check and filter query to filter by deleted_ts column

dao-api/src/main/pegasus/com/linkedin/metadata/internal/IngestionParams.pdl, dao-api/src/main/pegasus/pegasus/com/linkedin/metadata/events/IngestionAspectETag.pdl
metadata-models/metadata-dao has some limitation on adding new proto models. It requires the translated PDL files from OSS.
These files are generated from metadata-models proto.
N/A
=> [feat] add etag models

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/pegasus/com/linkedin/metadata/events/IngestionAspectETag.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
IngestionParams now can contain a list of IngestionETags (aspect name -> timestamp). If this is provided by user, we will use the provided timestamp for optimistic locking for given aspect.
The optimistic locking mechanism was already in place. Before it was locking only during the ingestion, now since we have given the eTags, the locking period can be extended for user to have read-modify-write consistency.
./graldew build
=> [feat] add with optimistic locking in BaseLocalDAO

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java
This pull request introduces enhancements to the `BaseVersionedAspectResource` class, focusing on integrating shadow DAO functionality for read operations. The changes aim to improve data consistency checks and logging while maintaining fallback mechanisms. Below is a summary of the most significant changes grouped by theme.
* Added a new method, `getLocalReadShadowDAO`, to retrieve the shadow DAO for read operations. This method returns `null` by default, allowing subclasses to override it as needed.
* Modified the `get` method to use the shadow DAO for retrieving aspects when available. If both local and shadow DAOs return values, the method compares them and logs any mismatches, falling back to the local DAO in case of discrepancies.
* Introduced the private helper method …
=> Add dual read to BaseVersionedAspectResource

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
This pull request introduces functionality to handle shadow relationship table backfills in the `BaseEntityResource` class. The most significant changes include adding a new method to perform the backfill and updating the existing backfill logic to delegate to this new method if a shadow DAO is available.
* **Delegation to Shadow DAO**: Updated the `backfillRelationshipTables` method to check for the presence of a shadow DAO (`getShadowLocalDAO`). If available, the method delegates the backfill operation to the newly introduced `backfillShadowRelationshipTables` method.
* **New Backfill Method**: Added the `backfillShadowRelationshipTables` method to handle the backfilling of shadow relationship tables. This method iterates over the provided URNs and aspects, retrieves relationship …
=> Added a method to backfill shadow relationship tables

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java
This pull request refines logging messages in the `BaseEntityResource` and `BaseVersionedAspectResource` classes to improve clarity and reduce verbosity. The changes primarily focus on simplifying log messages by removing detailed data outputs while retaining essential information and adding new log statements for specific conditions.
* **Simplified aspect mismatch logs**:
- In `getUrnAspectMapFromShadowDao` (`BaseEntityResource.java`), removed detailed comparison outputs for aspect mismatches, focusing instead on the URN and aspect name.
- In `getAspectFromReadShadowDAO` (`BaseVersionedAspectResource.java`), removed detailed local and shadow value outputs in mismatch logs, retaining only the URN and version details.
* **New logs for shadow-only and local-only scenarios**:
- Added …
=> Added logs for debugging dual read for EGG migration

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
This pull request enhances the handling of data discrepancies between the local DAO and the shadow DAO in the `BaseEntityResource` class. The most significant changes include adding logic to log warnings for shadow-only data, implementing a new method to compare and resolve aspect values between the two DAOs, and refining the logic for handling mismatched or missing aspect values.
* **Shadow DAO existence check and logging**: Added a check in the `get` method to log a warning if an entity exists in the shadow DAO but not in the local DAO, and to ignore shadow-only data. (`restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java`, [restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.javaR238-R240](diffhunk://#diff-ef2014126659a7045b6b1d4 …
=> [EGG Migration]: Bug fix for dual read

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
IngestionParams.IngestionETag should use field name (same as db column name).
added unit test
=> [fix] use aspect field name instead of class name

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
This PR addresses a bug where repeated calls to getShadowReadLocalDAO() within a single method invocation could yield inconsistent results due to dynamic evaluation of a LiX flag. This caused a NullPointerException when getShadowReadLocalDAO() returned null during an internal method call, despite being non-null earlier in the execution.
The logic in getInternalAspectsFromLocalDao(...) conditionally calls getInternalAspectsWithShadowComparison(...) based on whether getShadowReadLocalDAO() is null. However, getShadowReadLocalDAO() is backed by a LiX flag that may evaluate differently between calls. If the LiX value flips mid-execution, it results in the inner method dereferencing a null DAO.
We now cache the result of getShadowReadLocalDAO() in a local variable at the beginning of …
=> [EGG Migration] NPE fix for dual read

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-create-all-with-non-dollar-virtual-column-names.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql
This is PR#3 in a series of PRs which will contain code changes to support usage of deleted_ts column in DAO methods for read and write paths.
Prev:
PR#1 - https://github.com/linkedin/datahub-gma/pull/539
PR#2 - https://github.com/linkedin/datahub-gma/pull/544
1. Updated create implementation
* Update the SQL for create to follow a pattern like so:
```
INSERT INTO metadata_entity_foo (urn, a_urn, lastmodifiedon, lastmodifiedby,a_aspectfoo) 
VALUES (:urn, :a_urn, :lastmodifiedon, :lastmodifiedby,:aspect0) 
ON DUPLICATE KEY UPDATE a_aspectfoo= :aspect0,  deleted_ts = IF(deleted_ts IS NULL, CAST('DuplicateKeyException' AS UNSIGNED), deleted_ts);
```
3. Updated update implementation
* If this asset was previously marked for deletion and still not purged, updating the new aspect values and …
=> Updating method for create(), update() and delete() to handle soft delete by setting deleted_ts

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java
Some aspects are ingested as "pegasus.com.linkedin..." while some are ingested as "com.linkedin...". The relationship writer dao should treat these as equivalent for the purpose of removing relationships.
Added a unit test
=> fix(relationship): ignore 'pegasus.' prefix when comparing aspect FQCN

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java
Similar to #556 , making getLocalReadShadowDAO() pass as the parameter to keep the value consistent and not flip based on LiX
=> [EGG Migration]: Bug fix for NPE - part 2

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java
Relationship insertion performance can be potentially improved by combining multiple single-valued INSERT INTO statements into a single INSERT INTO statement with multiple values. Do that in batches of 1000.
Ref to the MySQL documentation on optimizing INSERT statement performance: https://dev.mysql.com/doc/refman/8.4/en/insert-optimization.html#:~:text=If%20you%20are%20inserting%20many,separate%20single%2Drow%20INSERT%20statements.
make sure existing relationship unit tests pass. add a new unit test ingesting a single relationship to make sure that case is covered as well.
=> feat(relationship ingestion): add multiple relationships in a single statement

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
metagalaxy has a max_allowed_packet size of `419430400` bytes (400 MB).
job_gms_corp: 1073741824 (~1 GB)
mg_db_1_corp: 1073741824 (~1 GB)
ai_metadata_prod: 419430400 (~400 MB)
Now that relationship ingestions are grouped into insert statements containing batches of relationships, there is a risk of hitting the max which will result in a stack overflow error.
Here is the SQL statement template:
```
INSERT INTO tableName (metadata, source, destination, source_type, destination_type, lastmodifiedon, lastmodifiedby, {aspect}) VALUES
(:metadata0, :source0, :destination0, :source_type0, :destination_type0, :lastmodifiedon, :lastmodifiedby, {:aspect}),
(:metadata1, :source1, :destination1, :source_type1, :destination_type1, :lastmodifiedon, :lastmodifiedby, {:aspect}),
...
```
Size estimates in …
=> fix(ingestion): reduce relationship insertion batch size from 1000 to 100

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
Reverts linkedin/datahub-gma#546
We ended by creating a separate service to perform the [backfill of relationship tables](https://github.com/linkedin-multiproduct/metadata-graph-assets/pull/369) from current database to new database. So, we don't need this change.
=> Revert "Added a method to backfill shadow relationship tables"

dao-api/src/main/pegasus/com/linkedin/metadata/query/Condition.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
Add ARRAY_CONTAINS condition to support the filtering case where you want to find if an aspect's array field contains the value you provide. This will be useful for labeling where the labels will be stored as an array of strings and the user is looking for all assets which have a particular label.
Add unit test and check the generated sql statement.
Unfortunately this cannot be properly tested since MariaDB (used for local testing) does not support the MEMBER OF function. Similar behavior can be achieved with JSON_CONTAINS but it is also slower than MEMBER OF. Further testing will happen at the service integration layer instead of here in the DAO library.
=> feat(filter): add ARRAY_CONTAINS condition for filtering

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
findRelationshipV4 is using logical expression in LocalRelationshipFilter, and we want to keep the use of filter consistent in findEntities too.
adding new findEntities API to allow use of logical expression in LocalRelationshipFilter. The old API should already use the updated logic in SQL building. This PR only changes the validation logic.
The old validation logic doesn't cover logical expression.
unit tests
=> [feat] add findEntitiesV2 to support logical expression filter

dao-api/src/main/pegasus/com/linkedin/metadata/events/IngestionTrackingContext.pdl, dao-api/src/main/pegasus/pegasus/com/linkedin/metadata/events/SubmissionType.pdl
To track the metadata from client side. The SubmissionType is needed to know which environment is request emitted from.
=> add SubmissionType in IngestionTrackingContext

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
A hot fix for destination URN edge case:
BUG=[META-22981](https://linkedin.atlassian.net/browse/META-22981)
BUG=[META-22917](https://linkedin.atlassian.net/browse/META-22917)
*Note: This is not the recommended parameterized query approach, which requires significant efforts and is planned to be implemented later, but a quick fix adding sql escaping for relationship to resolve the case mentioned in the ticket.
Unit tests
`./gradlew build`
Test with actual GQS flow:
- Currently without fix:
```
[chmeng@zany-earth metadata-graph-query]$ grpcurli --dv-auth SELF localhost:24572 proto.com.linkedin.metadatagraphquery.FindRelationshipsApi.get -d '{"key": {"destinationAssetFilter": {"criteria": [{"target": "proto.com.linkedin.metadata.asset.DatasetAsset", "path": "urn", "condition": …
```
=> Hot fix for META-22917

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
The existing listUrns query used a single SQL statement with `SELECT * , (SELECT COUNT(..)) AS _total_count`. This design caused MySQL to:
- Perform large in-memory sorts (filesort), especially when downstream passed `Integer.MAX_VALUE` as the page size.
- Fetch unnecessary columns (`SELECT *`) when only `urn` was needed.
Result: frequent Out of sort memory errors and inefficient queries.
- Split queries:
-- Run a dedicated `COUNT(*)` query to compute totalCount (no sort, no limit).
-- Run a separate page query (`SELECT urn … ORDER BY urn LIMIT :pageSize OFFSET :start`) for values.
- Removed `SELECT *`:
-- Only fetch urn in page queries.
- Updated toListResult:
-- Added a new overload that accepts (values, totalCount, start, pageSize).
-- No longer depends on _total_count embedded in each …
=> Splitting filter queries
