gradle/java-publishing.gradle
=> Generate POMs before uploading to bintray.

core-models/src/main/javaPegasus/com/linkedin/common/urn/TupleKey.java, core-models/src/main/javaPegasus/com/linkedin/common/urn/Urn.java, core-models/src/main/javaPegasus/com/linkedin/common/urn/UrnCoercer.java, core-models/src/main/javaPegasus/com/linkedin/common/urn/Urns.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseVersionedAspectResourceTest.java, version.properties
This should help us avoid more breakages when bringing in changes / pushing out changes. We're less likely to hit compiler errors due to bad references to Urn.
=> [Breaking] Update definition of URN to match LI's internal definition.

core-models-utils/README.md, core-models-utils/build.gradle, core-models-utils/src/main/java/com/linkedin/common/urn/Urns.java, dao-impl/ebean-dao/build.gradle, restli-resources/build.gradle, settings.gradle
This is need to avoid breaking LinkedIn's build.
=> Move "Urns" utility class to another module.

scripts/li-local-release.sh
=> feat: add a script for linkedin devs to release locally

gradle/java-publishing.gradle
=> feat: enable auto publishing new versions on bintray

testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/ElasticsearchIntegrationTestExtension.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/SearchIndexFactory.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/annotations/SearchIndexType.java
=> feat: finish off implementation ElasticsearchIntegrationTestExtension

testing/elasticsearch-dao-integ-testing/README.md, testing/elasticsearch-dao-integ-testing/build.gradle, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/asserts/BulkRequestsContainerAssert.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/asserts/SearchIndexAssert.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/asserts/SearchResultAssert.java
=> feat: add some simple assertions to help with testing

testing/elasticsearch-dao-integ-testing-docker/src/test/java/com/linkedin/metadata/testing/ExampleSanityTest.java, testing/elasticsearch-dao-integ-testing/src/main/java/com/linkedin/metadata/testing/BaseSearchSanityTests.java, testing/test-models/src/main/java/com/linkedin/testing/TestUtils.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BarUrn.java
=> feat: add base class for search sanity tests

build.gradle, testing/elasticsearch-dao-integ-testing-docker-7/src/test/java/com/linkedin/metadata/testing/ExampleSanityTest.java, testing/elasticsearch-dao-integ-testing-docker/src/test/java/com/linkedin/metadata/testing/ExampleSanityTest.java
To pick up https://github.com/testcontainers/testcontainers-java/issues/3166
=> fix: update testcontainers

gradle-plugins/metadata-annotations-lib/build.gradle, gradle-plugins/metadata-annotations-schema/build.gradle, gradle-plugins/metadata-annotations-test-models/build.gradle, gradle-plugins/metadata-events-generator-lib/build.gradle, gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/EventSpec.java, gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/SchemaGenerator.java, gradle-plugins/metadata-events-generator-plugin/build.gradle, gradle-plugins/metadata-events-generator-plugin/src/main/java/com/linkedin/metadata/gradle/MetadataEventsGeneratorPlugin.java
=> feat: enable publishing the MXE v5 plugin to bintray.

testing/elasticsearch-dao-integ-testing-docker-7/src/test/java/com/linkedin/metadata/testing/ESBrowseDaoIntegTest.java, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/mappings.json, testing/elasticsearch-dao-integ-testing-docker-7/src/test/resources/pizza/settings.json, testing/elasticsearch-dao-integ-testing-docker/src/test/java/com/linkedin/metadata/testing/ESBrowseDaoIntegTest.java, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/mappings.json, testing/elasticsearch-dao-integ-testing-docker/src/test/resources/pizza/settings.json, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaSearchDocument.pdl
=> feat: add browse DAO integration tests for elasticsearch

docs/developers.md
=> (docs): updating onboarding docs to fix repo name

.github/actions/release/action.yml, build.gradle, docs/how/releases/continuous-releases.md, gradle/ci-release.gradle, gradle/java-publishing.gradle
Bintray is going to be deprecated soon, prepare to switch to our artifactory instance.
=> Setup publishing to LI artifactory

.github/actions/release/action.yml
Minimal PR so its easy to rollback if needed. Once we're ok with this we can delete all the bintray code in a follow up.
=> Stop publishing to bintray.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
I've left the flag in place for now, I've just flipped the default.
=> fix: Make the default query for batch gets use UNION rather than OR.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
This can lead to a stack overflow, but per ebean it is not needed and recommended that we use findNative instead.
https://groups.google.com/g/ebean/c/ILpii41dJPA/m/lHhM4WCPBwAJ
=> fix: do not parse ebean union query

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
=> fix: Produce aspect specific MAE for backfill

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
We currently only support full text match for string values in SCSI. This change extends support to prefix-match which will be useful for autocomplete functionality.
=> feat: add support for prefix based string match in SCSI

gradle-plugins/metadata-events-generator-plugin/src/main/java/com/linkedin/metadata/gradle/tasks/GenerateMetadataEventsTask.java
=> fix: fix gradle caching issue

repositories.gradle
=> fix(build): remove dependency of bintray

gradle-plugins/metadata-events-generator-lib/src/main/java/com/linkedin/metadata/generator/SchemaGeneratorUtil.java
=> fix(util): Made util functions in SchemaGeneratorUtil public

dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectBaz.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/TyperefPizzaInfo.pdl
=> feat: support typeref in RecordUtils.

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/BaseBrowseConfig.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
Use executor service to call ES in parallel and add config to enable/disable map execution mode.
=> feat: use executor service to call ES in parallel

build.gradle, dao-impl/elasticsearch-dao-7/build.gradle, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/BaseBrowseConfig.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
Locally tested the change with snapshot version.
=> feat: Implements caching in ESBrowseDAO

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/PizzaOrder.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/TyperefPizzaAspect.pdl
=> feat: typeref to a record is supported as valid aspect type

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
=> fix: Catch any exception when preloading cache during DAO instantiation

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/BaseTrackingManager.java, dao-api/src/main/java/com/linkedin/metadata/dao/tracking/DummyTrackingManager.java, dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/tracking/DummyTrackingManagerTest.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, docs/advanced/tracking.md, version.properties
- Define the generic base tracking manager and process states to be extended.
- Bump up minor version due to backward compatible DAO API changes.
=> feat: Create base tracking manager and integrate states in ESSearchDAO.

docs/advanced/aspect-routing.md, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingGmsClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
=> feat: add base class for aspect routing and implement get endpoint

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingGmsClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
=> feat: implement ingest endpoint for aspect routing

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
=> fix: increase thread count in ESBrowseDAO

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
=> feat: implement getSnapshot endpoint

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEBeanLocalAccess.java
=> META-16566 feat: add interface for new schema CRUD access

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingGmsClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseVersionedAspectResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliUtils.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseVersionedAspectResourceTest.java
=> feat: Add findByUrns endpoint to BaseVersionedAspectResource

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectV2Resource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableAspectResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectV2ResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseSearchableAspectResourceTest.java
=> feat: Create top level resource BaseAspectV2Resource

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
=> fix: Bug fix on backfill action for BaseAspectRoutingResource

build.gradle, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql
=> (feat):Create EBeanLocalAccess to support data access on new schema

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
=> fix: Need to preserve order in backfill result from local dao

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> feat: support count aggregate in ebean local access

build.gradle, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java
* dependency was breaking some downstreams' dependency validation checks
=> fix: don't use apache collections4

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
=> fix: fix bugs and unit tests on new schema

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
=> feat: add audit info into metadata for entity tables

dao-api/src/main/java/com/linkedin/metadata/dao/exception/MissingAnnotationException.java, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AspectColumn.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AspectColumnMetadata.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AspectColumnName.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectBar.pdl
=> feat: Support annotation-based column naming

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ClassUtils.java, dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> feat: add EbeanLocalRelationshipQueryDAO implementaion

dao-api/src/main/java/com/linkedin/metadata/dao/ListResult.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEBeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/gma-create-all.sql, dao-impl/ebean-dao/src/test/resources/gma-drop-all.sql, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql
=> fix: fix most EbeanLocalDAO unit tests for new schema

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql
=> fix: Fix json parsing for AuditedAspect

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
=> fix: Minor code quality improvements.

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql
12 out of 486 tests failing:
testAddFailedAfterRetry (new schema, dual schema) 4x
testGetCapsSensitivity (new schema, dual schema) 4x
testListUrnsForSoftDeletedAspect (new schema) 2x
testListUrnsOffsetPagination (new schema) 2x
=> fix(new schema): fix vast majority of new schema unit tests

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/MysqlDevInstance.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BurgerUrn.java, testing/test-models/src/main/javaPegasus/com/linkedin/testing/urn/BurgerUrnCoercer.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectBar.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectBaz.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectFoo.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/BurgerUrn.pdl
=> fix: Use annotation based column name

dao-api/src/main/java/com/linkedin/metadata/dao/BaseReadDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> fix(new schema): fix soft-deletion of aspects and remaining new schema unit tests

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/MultiHopsTraversalSqlGenerator.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/SampleLocalRelationshipRegistryImpl.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/BelongsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/PairsWithLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/ReportsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/VersionOfLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql, testing/test-models/src/main/pegasus/com/linkedin/testing/BarSnapshot.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/FooSnapshot.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/PairsWith.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/ReportsTo.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/VersionOf.pdl
=> feat: implement local relationship query DAO part 2

build.gradle, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java
=> fix: fix logs and minor bugs

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
=> fix(new schema): add createdfor field to AuditedAspect

build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/SchemaEvolutionManager.java, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/MysqlDevInstance.java, dao-impl/ebean-dao/src/test/resources/db/evolution/V1__create_foo_entity_table.sql, dao-impl/ebean-dao/src/test/resources/db/evolution/V2__create_bar_entity_table.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql, dao-impl/ebean-dao/src/test/resources/schema-evolution-create-all.sql
=> feat: Track DB evolution with flyway

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EbeanServerUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
=> fix: Code style fix and refactorings

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/pegasus/com/linkedin/metadata/backfill/BackfillMode.pdl, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java
=> feat(new schema): implement backfill API to streamline old -> new schema migration

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/builder/LocalRelationshipBuilderRegistry.java, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/SampleLocalRelationshipRegistryImpl.java, dao-impl/ebean-dao/src/test/resources/metadata-schema-create-all.sql, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, testing/test-models/src/main/java/com/linkedin/testing/TestUtils.java, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/AspectFooBar.pdl
=> feat: Integrate local relationship writer DAO

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> fix: replace WITH with MySQL backward compatible syntax

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
All existing unit tests passed.
=> fix: Clean up _useUnionForBatch and _useOptimisticLocking

gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/AspectAnnotation.pdl, gradle-plugins/metadata-annotations-schema/src/main/pegasus/com/linkedin/metadata/annotations/ColumnNameAnnotation.pdl
=> fix(new schema): add @gma.aspect.column.name annotation

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all.sql, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, gradle-plugins/metadata-annotations-lib/src/test/java/com/linkedin/metadata/annotations/GmaAnnotationParserTest.java, gradle-plugins/metadata-annotations-test-models/src/main/pegasus/com/linkedin/testing/AnnotatedAspectBar.pdl
=> feat(new schema): add a_urn column to help with urn path extraction

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-access-create-all.sql, testing/test-models/src/main/java/com/linkedin/testing/TestUtils.java, testing/test-models/src/main/pegasus/com/linkedin/testing/BurgerSnapshot.pdl
=> fix: escape reserved char in urn

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
=> Surface json parse exception

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
=> feat(new schema): add getter for Ebean DAO's schema config

dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java, dao-impl/ebean-dao/src/test/resources/ebean-local-dao-create-all.sql, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectAttributes.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAspectUnion.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityValue.pdl
=> Support filter on array value for new schema

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
=> feat(new schema): allow public access to EbeanLocalAccess::readSqlRows

dao-api/src/main/java/com/linkedin/metadata/dao/ListResult.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java
=> fix(new schema): introduce more verbose log messages for compareResults

dao-api/src/main/pegasus/com/linkedin/metadata/query/AspectField.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/LocalRelationshipCriterion.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/LocalRelationshipFilter.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/LocalRelationshipValue.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/RelationshipField.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/UrnField.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/MultiHopsTraversalSqlGenerator.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> feat(new schema): Redesign local relationship query filter

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
=> fix(new schema): fix logs to ignore ms component of timestamps

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLStatementUtilsTest.java
=> update the sql template to include lastmodifiedon

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
=> enable / disable maev4

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
"""
`<feat> : add additional logging for observability`
The direct SQL methodology introduced [here](https://github.com/linkedin/datahub-gma/pull/252) was insufficient at de-duplicating insertions, so the logging introduced here should help give increased visibility into what SQL command exactly is being run for both insertion and updates.
"""
=> Add additional logging for observability

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java
=> (fix) add log for converted ES query

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
##
- Add ES output log to ES5 implementation
- Add default aspect manager instantiation
=> add search log to es5 impl

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
This fix is to workaround the Inject setter does not behave properly on the TMS side.
=> (fix) implement a get interface for aspect routing manager

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
=> (fix) fix an NPE in error log printing

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/tracking/TrackingUtilsTest.java
=> fix(tracking): fix random UUID generation

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseSingleAspectEntitySimpleKeyResourceTest.java
=> feat(tracking): add ingestWithTracking method to BaseEntityResource

dao-api/src/main/java/com/linkedin/metadata/dao/internal/BaseRemoteWriterDAO.java
Forgot to make this change as part of #272.
=> feat(tracking): add createWithTracking method to BaseRemoteWriterDAO

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
- refactored some constructors from @VisibleForTesting --> private if they were not used in tests
- reorganized constructors so that public constructors are all on top
=> fix(tracking): add tracking params to EbeanLocalDAO constructors

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
=> feat(tracking): add failure event process states to MAE consumer jobs

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
Remove legacy code of single aspect routing implementation
=> code cleanup for multi-aspect routing implementation

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
=> more aspect routing aspect cleanup

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingGmsClient.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectV2Resource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectV2ResourceTest.java
- Also added to BaseAspectV2Resource
=> feat(tracking): add tracking to BaseAspectRoutingResource

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
=> Add Ebean find methodology constructor with tracking manager.

build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
=> feat(tracking): add errorType and aspectType dimension enums

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
=> feat(tracking): add originalEmitTime dimension

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
Implement the SQL version of getLatest() to resolve the duplicity issue in EBean.find()
Context discussion from: https://github.com/ebean-orm/ebean/issues/3080
=> implement a SQL substitution for get latest

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
=> feat: add labels needed for visibility expension

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableAspectResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java
=> Mark method public

restli-resources/src/main/pegasus/com/linkedin/metadata/restli/BackfillResult.pdl
=> Add relationship to backfill result

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
- Add flag to overwrite latest version in metadata_aspect if enabled.
- Temporary measure and will be removed once TMS cleans up (i.e. deletes) the metadata_aspect table completely.
=> feature(new schema): add flag to write only latest version to metadata_aspect

dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EmbeddedMariaInstance.java, dao-impl/ebean-dao/src/test/resources/ebean-local-relationship-dao-create-all.sql, testing/test-models/src/main/pegasus/com/linkedin/testing/localrelationship/ConsumeFrom.pdl
Add an unit test to show how to query relationship with filtering on relationship metadata.
=> Add unit test to cover query for relationship metadata

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
refactor to simplify LocalRelationshipCriterion creation in EbeanLocalRelationshipQueryDAOTest
=> create util func for LocalRelationshipCriterion creation

dao-api/src/main/java/com/linkedin/metadata/dao/tracking/TrackingUtils.java
for tracking purpose in mle-consumer-job (samza)
=> Add MLE process states in TrackingUtils

core-models/src/main/pegasus/com/linkedin/avro2pegasus/events/KafkaAuditHeader.pdl
Context:
https://linkedin-randd.slack.com/archives/CG4JHTZ3J/p1704236896576089
=> resolve kafka audit header confit

dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java
Added new search function to allow user to pass in a list of criteria which will be used as aggregations on the metadata result.
Currently, ESSearchDAO doesn't support multi filters on metadata result. If user pass in a list of post filters, the metadata result will be aggregated by those filters individually. For example, if we have filter1: projectGroupName=A, and filter2: status=published, the metadata result will have each bucket with two non-overlapping aggregations, but not an aggregation with result that both satisfy filter1 AND filter2.
This change will replace the original aggregations (each with an individual filter) with one aggregation that has those filters AND'd together, so this aggregation will be used to filter out metadata result that satisfy all filters.
The old search …
=> implement AND logic multi aggregations in ESSearchDAO

dao-api/src/main/java/com/linkedin/metadata/dao/builder/BaseLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/BelongsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/PairsWithLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/ReportsToLocalRelationshipBuilder.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/builder/VersionOfLocalRelationshipBuilder.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
Bound relationship type in LocalRelationshipUpdates.
A followup improvement to https://github.com/linkedin/datahub-gma/pull/342
=> (fix) bound relationship type in LocalRelationshipUpdates

dao-api/src/main/pegasus/com/linkedin/metadata/aspect/AuditedAspect.pdl, dao-api/src/main/pegasus/com/linkedin/metadata/query/ListResultMetadata.pdl, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java
To persist emitter information for establishing emitter priority or other usages.
=> feat: Persist emitter from ingestionTrackingContext in new entity tables.

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, dao-api/src/main/java/com/linkedin/metadata/dao/ingestion/BaseLambdaFunction.java, dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java, dao-api/src/test/java/com/linkedin/metadata/dao/ingestion/SampleLambdaFunctionRegistryImpl.java, dao-api/src/test/java/com/linkedin/metadata/dao/ingestion/lambda/MergeBarAspectFooBarLambdaFunction.java
=> feat: invoke pre-ingestion lambdas in local DAO.

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAsset.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/InternalEntityAspectUnion.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/InternalEntitySnapshot.pdl, validators/src/main/java/com/linkedin/metadata/validator/AssetValidator.java
Introduce Assets models and its model utilities and deprecate Snapshots.
unit tests
=> feat: build asset models utils.

restli-resources/src/main/java/com/linkedin/metadata/restli/lix/DummyResourceLix.java, restli-resources/src/main/java/com/linkedin/metadata/restli/lix/ResourceLix.java
To create experimental controller interface for API testing.
=> feat: create experimental controller interface.

dao-api/src/main/java/com/linkedin/metadata/dao/utils/ModelUtils.java, dao-api/src/test/java/com/linkedin/metadata/dao/utils/ModelUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/EntityAsset.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/InternalEntityAspectUnion.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/singleaspectentity/InternalEntityAspectUnion.pdl, testing/test-models/src/main/pegasus/com/linkedin/testing/singleaspectentity/InternalEntitySnapshot.pdl
=> feat: build conversion utils.

restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java
add an getAsset restli constant
=> add getAsset restli constant

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java
Remove IngestionTrackingContext from ingestAsset API template.
=> remove tracking context from ingestAsset API

dao-api/src/main/java/com/linkedin/metadata/dao/producer/BaseMetadataEventProducer.java, dao-api/src/main/java/com/linkedin/metadata/dao/producer/DummyMetadataEventProducer.java, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java
emit search related metrics from  SearchDAO
=> emit search related metrics from  SearchDAO

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
adding resource lix setter method
=> add resource lix setter method

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseBrowsableEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntityResourceTest.java, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseEntitySimpleKeyResourceTest.java
add resource lix getter method to allow being override by resource implementation. 
=> add lix getter method

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectV2Resource.java
Add batchGet to BaseAspectV2Resource
Nothing
=> Add batchGet for BaseAspectV2Resource

dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
- add necessary logging for testing pre-update ingestion routing
=> add logging for pre update routing

build.gradle, dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/search/ESBulkWriterDAO.java, gradle/wrapper/gradle-wrapper.properties, restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java, testing/elasticsearch-dao-integ-testing-7/src/main/java/com/linkedin/metadata/testing/SearchIndex.java, testing/elasticsearch-dao-integ-testing-7/src/main/java/com/linkedin/metadata/testing/SearchIndexFactory.java
Bump several dependencies which are preventing the ELR process from completing successfully.
`./gradlew build --scan`, check build scan
=> bump several dependencies, use gradle 6

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java
After migrating to Hosted Search, the document field may not be populated. Hence, when fetching the urns. Try to read from the SearchResultMetadata.
build
=> Fetch urns from search result metadata

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java
Mostly to trigger another build
nada
=> Make it more succinct

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java, restli-resources/src/main/java/com/linkedin/metadata/restli/BaseSingleAspectSearchableEntityResource.java
Don't want it to be null
`./gradlew build`
=> Add urn class in constructor for BaseSingleAspectSearchableEntityResource

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
Accidentally merged before build check was passed.
=> fix: bug fix for #470

dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/EBeanDAOUtilsTest.java, testing/test-models/src/main/pegasus/com/linkedin/testing/AspectWithDefaultValue.pdl
add more unit test for the default value behavior
Just add new unit test
=> add more unit test for the default value behavior

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
Previously, optimistic locking had the following behavior:
in NEW_SCHEMA and DUAL_SCHEMA modes:
getLatest from entity table
add with optimistic locking to aspect table using old timestamp from entity table
in OLD_SCHEMA mode:
getLatest from aspect table
add with optimistic locking to aspect table using old timestamp from aspect table
Now, use the aspect table when in DUAL_SCHEMA mode which makes sense since DUAL_SCHEMA mode will read from both tables but eventually return the result from the old schema table anyways.
update unit tests
=> fix(dual schema): use aspect table as SOT for optimistic locking in DUAL_SCHEMA mode

dao-api/src/main/java/com/linkedin/metadata/dao/utils/GraphUtils.java
produces needs to be capitalized to Produces
testing in locally deployed ai-metadata-gms
=> fix(aim): fix typo in checksameSourceUrn

build.gradle, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTestWithoutServiceIdentifier.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java
DDL operations on large table can be dangerous. For example, adding an index to a table contains a few millions of rows will likely take hour or so to complete and cause performance impact to database.
Instead of blindly applying the evolution scripts, this PR aims to classify the SQL script into low and high risk category.
- For low risk ones, flyway will automatically apply the script to maximize productivity.
- For high risk ones, we will work MySQL team to get it applied properly.
The low risk DDL are
- Create new table
- Add new column to existing table
The high risk DDL are
- Create index on table with more than 500K estimated row count.
- Drop table
For high risk script, we will need to manually mark it as completed in version table after MySQL team applied the script.
unit test
=> [feat] Smart schema evolution

dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
Fix the issue for loading sql script.
=> Bug fix - Fix the issue for loading sql script.

dao-api/src/main/java/com/linkedin/metadata/dao/SchemaEvolutionManager.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java
Pass in the required param `enableSchemaCheck` from EbeanLocalDao.
existing test
=> Modify interface for schema evolution

build.gradle, dao-api/src/main/java/com/linkedin/metadata/dao/SchemaEvolutionManager.java, dao-impl/ebean-dao/build.gradle, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java, dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTestWithoutServiceIdentifier.java, dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLSchemaUtilsTest.java
We will be using Pretzel for deployment in EI and Corp, that's why we don't need the smart schema evolution. All the scripts (low risk and high risk) will be done through Pretzel.
=> Undo Flyway smart evolution to support Pretzel

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Adding shadow write to BaseAspectRoutingResource
=> Adding shadow write to BaseAspectRoutingResource

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
Change rawAdd to add for shadowDao
=> Fix bug: Change rawAdd to add for shadowDao

restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
This pull request refines the logic for determining which aspect value to use in the `getInternalAspectsWithShadowComparison` method of `BaseAspectRoutingResource.java`. It introduces clearer handling for different cases of local and shadow data presence, improves logging messages, and adjusts the behavior for shadow-only data.
Key changes:
* Refactored the conditional logic to explicitly handle four cases: both local and shadow present and equal, both present but not equal, only shadow present, and only local present. This improves code readability and maintainability.
* Enhanced log messages to provide more context about each case, including warnings for mismatches or shadow-only data and better explanations of the actions taken.
* Modified the behavior for the "only shadow present" …
=> [EGG Migration] Bug fix for dual read
